// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef SLATE_TextLayout_generated_h
#error "TextLayout.generated.h already included, missing '#pragma once' in TextLayout.h"
#endif
#define SLATE_TextLayout_generated_h

#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Slate_Public_Framework_Text_TextLayout_h


#define FOREACH_ENUM_ETEXTJUSTIFY(op) \
	op(ETextJustify::Left) \
	op(ETextJustify::Center) \
	op(ETextJustify::Right) 
PRAGMA_ENABLE_DEPRECATION_WARNINGS
