// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#ifndef FOLIAGEEDIT_ActorFactoryProceduralFoliage_generated_h
	#include "Private/ActorFactoryProceduralFoliage.h"
#endif
#ifndef FOLIAGEEDIT_FoliageType_ISMThumbnailRenderer_generated_h
	#include "Public/FoliageType_ISMThumbnailRenderer.h"
#endif
#ifndef FOLIAGEEDIT_FoliageTypeFactory_generated_h
	#include "Private/FoliageTypeFactory.h"
#endif
#ifndef FOLIAGEEDIT_LandscapeGrassTypeFactory_generated_h
	#include "Private/LandscapeGrassTypeFactory.h"
#endif
#ifndef FOLIAGEEDIT_ProceduralFoliageSpawnerFactory_generated_h
	#include "Private/ProceduralFoliageSpawnerFactory.h"
#endif
