// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "Private/GameplayDebuggerPrivate.h"
#include "GameplayDebugger.generated.dep.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
void EmptyLinkFunctionForGeneratedCodeGameplayDebugger() {}
class UScriptStruct* FGDTCustomViewNames::StaticStruct()
{
	static class UScriptStruct* Singleton = NULL;
	if (!Singleton)
	{
		extern GAMEPLAYDEBUGGER_API class UScriptStruct* Z_Construct_UScriptStruct_FGDTCustomViewNames();
		extern GAMEPLAYDEBUGGER_API uint32 Get_Z_Construct_UScriptStruct_FGDTCustomViewNames_CRC();
		extern GAMEPLAYDEBUGGER_API class UPackage* Z_Construct_UPackage_GameplayDebugger();
		Singleton = GetStaticStruct(Z_Construct_UScriptStruct_FGDTCustomViewNames, Z_Construct_UPackage_GameplayDebugger(), TEXT("GDTCustomViewNames"), sizeof(FGDTCustomViewNames), Get_Z_Construct_UScriptStruct_FGDTCustomViewNames_CRC());
	}
	return Singleton;
}
static FCompiledInDeferStruct Z_CompiledInDeferStruct_UScriptStruct_FGDTCustomViewNames(FGDTCustomViewNames::StaticStruct, TEXT("/Script/GameplayDebugger"));
static struct FScriptStruct_GameplayDebugger_StaticRegisterNativesFGDTCustomViewNames
{
	FScriptStruct_GameplayDebugger_StaticRegisterNativesFGDTCustomViewNames()
	{
		UScriptStruct::DeferCppStructOps(FName(TEXT("GDTCustomViewNames")),new UScriptStruct::TCppStructOps<FGDTCustomViewNames>);
	}
} ScriptStruct_GameplayDebugger_StaticRegisterNativesFGDTCustomViewNames;
	void UGameplayDebuggerSettings::StaticRegisterNativesUGameplayDebuggerSettings()
	{
	}
	IMPLEMENT_CLASS(UGameplayDebuggerSettings, 3023913481);
static class UEnum* EAIDebugDrawDataView_StaticEnum()
{
	static class UEnum* Singleton = NULL;
	if (!Singleton)
	{
		extern GAMEPLAYDEBUGGER_API class UEnum* Z_Construct_UEnum_GameplayDebugger_EAIDebugDrawDataView();
		extern GAMEPLAYDEBUGGER_API class UPackage* Z_Construct_UPackage_GameplayDebugger();
		Singleton = GetStaticEnum(Z_Construct_UEnum_GameplayDebugger_EAIDebugDrawDataView, Z_Construct_UPackage_GameplayDebugger(), TEXT("EAIDebugDrawDataView"));
	}
	return Singleton;
}
static FCompiledInDeferEnum Z_CompiledInDeferEnum_UEnum_EAIDebugDrawDataView(EAIDebugDrawDataView_StaticEnum, TEXT("/Script/GameplayDebugger"));
static class UEnum* EDebugComponentMessage_StaticEnum()
{
	static class UEnum* Singleton = NULL;
	if (!Singleton)
	{
		extern GAMEPLAYDEBUGGER_API class UEnum* Z_Construct_UEnum_GameplayDebugger_EDebugComponentMessage();
		extern GAMEPLAYDEBUGGER_API class UPackage* Z_Construct_UPackage_GameplayDebugger();
		Singleton = GetStaticEnum(Z_Construct_UEnum_GameplayDebugger_EDebugComponentMessage, Z_Construct_UPackage_GameplayDebugger(), TEXT("EDebugComponentMessage"));
	}
	return Singleton;
}
static FCompiledInDeferEnum Z_CompiledInDeferEnum_UEnum_EDebugComponentMessage(EDebugComponentMessage_StaticEnum, TEXT("/Script/GameplayDebugger"));
	void UGameplayDebuggingComponent::ClientEnableTargetSelection(bool bEnable)
	{
		GameplayDebuggingComponent_eventClientEnableTargetSelection_Parms Parms;
		Parms.bEnable=bEnable ? true : false;
		ProcessEvent(FindFunctionChecked(GAMEPLAYDEBUGGER_ClientEnableTargetSelection),&Parms);
	}
	void UGameplayDebuggingComponent::ServerCollectNavmeshData(FVector_NetQuantize10 TargetLocation)
	{
		GameplayDebuggingComponent_eventServerCollectNavmeshData_Parms Parms;
		Parms.TargetLocation=TargetLocation;
		ProcessEvent(FindFunctionChecked(GAMEPLAYDEBUGGER_ServerCollectNavmeshData),&Parms);
	}
	void UGameplayDebuggingComponent::ServerDiscardNavmeshData()
	{
		ProcessEvent(FindFunctionChecked(GAMEPLAYDEBUGGER_ServerDiscardNavmeshData),NULL);
	}
	void UGameplayDebuggingComponent::StaticRegisterNativesUGameplayDebuggingComponent()
	{
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"ClientEnableTargetSelection",(Native)&UGameplayDebuggingComponent::execClientEnableTargetSelection);
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"OnCycleDetailsView",(Native)&UGameplayDebuggingComponent::execOnCycleDetailsView);
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"OnRep_PathCorridorData",(Native)&UGameplayDebuggingComponent::execOnRep_PathCorridorData);
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"OnRep_UpdateBlackboard",(Native)&UGameplayDebuggingComponent::execOnRep_UpdateBlackboard);
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"OnRep_UpdateEQS",(Native)&UGameplayDebuggingComponent::execOnRep_UpdateEQS);
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"OnRep_UpdateNavmesh",(Native)&UGameplayDebuggingComponent::execOnRep_UpdateNavmesh);
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"ServerCollectNavmeshData",(Native)&UGameplayDebuggingComponent::execServerCollectNavmeshData);
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"ServerDiscardNavmeshData",(Native)&UGameplayDebuggingComponent::execServerDiscardNavmeshData);
		FNativeFunctionRegistrar::RegisterFunction(UGameplayDebuggingComponent::StaticClass(),"ServerReplicateData",(Native)&UGameplayDebuggingComponent::execServerReplicateData);
	}
	IMPLEMENT_CLASS(UGameplayDebuggingComponent, 3717676002);
	void UGameplayDebuggingControllerComponent::StaticRegisterNativesUGameplayDebuggingControllerComponent()
	{
	}
	IMPLEMENT_CLASS(UGameplayDebuggingControllerComponent, 576909838);
	void AGaneplayDebuggerProxyHUD::StaticRegisterNativesAGaneplayDebuggerProxyHUD()
	{
	}
	IMPLEMENT_CLASS(AGaneplayDebuggerProxyHUD, 1045589006);
	void AGameplayDebuggingHUDComponent::StaticRegisterNativesAGameplayDebuggingHUDComponent()
	{
	}
	IMPLEMENT_CLASS(AGameplayDebuggingHUDComponent, 3391882787);
	void AGameplayDebuggingReplicator::ClientAutoActivate()
	{
		ProcessEvent(FindFunctionChecked(GAMEPLAYDEBUGGER_ClientAutoActivate),NULL);
	}
	void AGameplayDebuggingReplicator::ClientEnableTargetSelection(bool bEnable, APlayerController* Context)
	{
		GameplayDebuggingReplicator_eventClientEnableTargetSelection_Parms Parms;
		Parms.bEnable=bEnable ? true : false;
		Parms.Context=Context;
		ProcessEvent(FindFunctionChecked(GAMEPLAYDEBUGGER_ClientEnableTargetSelection),&Parms);
	}
	void AGameplayDebuggingReplicator::ClientReplicateMessage(AActor* Actor, uint32 InMessage, uint32 DataView)
	{
		GameplayDebuggingReplicator_eventClientReplicateMessage_Parms Parms;
		Parms.Actor=Actor;
		Parms.InMessage=InMessage;
		Parms.DataView=DataView;
		ProcessEvent(FindFunctionChecked(GAMEPLAYDEBUGGER_ClientReplicateMessage),&Parms);
	}
	void AGameplayDebuggingReplicator::ServerReplicateMessage(AActor* Actor, uint32 InMessage, uint32 DataView)
	{
		GameplayDebuggingReplicator_eventServerReplicateMessage_Parms Parms;
		Parms.Actor=Actor;
		Parms.InMessage=InMessage;
		Parms.DataView=DataView;
		ProcessEvent(FindFunctionChecked(GAMEPLAYDEBUGGER_ServerReplicateMessage),&Parms);
	}
	void AGameplayDebuggingReplicator::ServerSetActorToDebug(AActor* InActor)
	{
		GameplayDebuggingReplicator_eventServerSetActorToDebug_Parms Parms;
		Parms.InActor=InActor;
		ProcessEvent(FindFunctionChecked(GAMEPLAYDEBUGGER_ServerSetActorToDebug),&Parms);
	}
	void AGameplayDebuggingReplicator::StaticRegisterNativesAGameplayDebuggingReplicator()
	{
		FNativeFunctionRegistrar::RegisterFunction(AGameplayDebuggingReplicator::StaticClass(),"ClientAutoActivate",(Native)&AGameplayDebuggingReplicator::execClientAutoActivate);
		FNativeFunctionRegistrar::RegisterFunction(AGameplayDebuggingReplicator::StaticClass(),"ClientEnableTargetSelection",(Native)&AGameplayDebuggingReplicator::execClientEnableTargetSelection);
		FNativeFunctionRegistrar::RegisterFunction(AGameplayDebuggingReplicator::StaticClass(),"ClientReplicateMessage",(Native)&AGameplayDebuggingReplicator::execClientReplicateMessage);
		FNativeFunctionRegistrar::RegisterFunction(AGameplayDebuggingReplicator::StaticClass(),"OnRep_AutoActivate",(Native)&AGameplayDebuggingReplicator::execOnRep_AutoActivate);
		FNativeFunctionRegistrar::RegisterFunction(AGameplayDebuggingReplicator::StaticClass(),"ServerReplicateMessage",(Native)&AGameplayDebuggingReplicator::execServerReplicateMessage);
		FNativeFunctionRegistrar::RegisterFunction(AGameplayDebuggingReplicator::StaticClass(),"ServerSetActorToDebug",(Native)&AGameplayDebuggingReplicator::execServerSetActorToDebug);
	}
	IMPLEMENT_CLASS(AGameplayDebuggingReplicator, 3849389917);
FName GAMEPLAYDEBUGGER_ClientAutoActivate = FName(TEXT("ClientAutoActivate"));
FName GAMEPLAYDEBUGGER_ClientEnableTargetSelection = FName(TEXT("ClientEnableTargetSelection"));
FName GAMEPLAYDEBUGGER_ClientReplicateMessage = FName(TEXT("ClientReplicateMessage"));
FName GAMEPLAYDEBUGGER_ServerCollectNavmeshData = FName(TEXT("ServerCollectNavmeshData"));
FName GAMEPLAYDEBUGGER_ServerDiscardNavmeshData = FName(TEXT("ServerDiscardNavmeshData"));
FName GAMEPLAYDEBUGGER_ServerReplicateMessage = FName(TEXT("ServerReplicateMessage"));
FName GAMEPLAYDEBUGGER_ServerSetActorToDebug = FName(TEXT("ServerSetActorToDebug"));
#if USE_COMPILED_IN_NATIVES
// Cross Module References
	COREUOBJECT_API class UClass* Z_Construct_UClass_UObject();
	ENGINE_API class UScriptStruct* Z_Construct_UScriptStruct_FVector_NetQuantize10();
	ENGINE_API class UClass* Z_Construct_UClass_UPrimitiveComponent();
	ENGINE_API class UClass* Z_Construct_UClass_AActor_NoRegister();
	COREUOBJECT_API class UScriptStruct* Z_Construct_UScriptStruct_FVector();
	AIMODULE_API class UClass* Z_Construct_UClass_UEQSQueryResultSourceInterface_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_UActorComponent();
	SLATE_API class UScriptStruct* Z_Construct_UScriptStruct_FInputChord();
	ENGINE_API class UClass* Z_Construct_UClass_UInputComponent_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_AHUD();
	ENGINE_API class UClass* Z_Construct_UClass_AActor();
	ENGINE_API class UClass* Z_Construct_UClass_APlayerController_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_UCanvas_NoRegister();
	ENGINE_API class UClass* Z_Construct_UClass_UTexture2D_NoRegister();

	GAMEPLAYDEBUGGER_API class UScriptStruct* Z_Construct_UScriptStruct_FGDTCustomViewNames();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_UGameplayDebuggerSettings_NoRegister();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_UGameplayDebuggerSettings();
	GAMEPLAYDEBUGGER_API class UEnum* Z_Construct_UEnum_GameplayDebugger_EAIDebugDrawDataView();
	GAMEPLAYDEBUGGER_API class UEnum* Z_Construct_UEnum_GameplayDebugger_EDebugComponentMessage();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_ClientEnableTargetSelection();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnCycleDetailsView();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_PathCorridorData();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateBlackboard();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateEQS();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateNavmesh();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_ServerCollectNavmeshData();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_ServerDiscardNavmeshData();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_ServerReplicateData();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_UGameplayDebuggingComponent_NoRegister();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_UGameplayDebuggingComponent();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_UGameplayDebuggingControllerComponent_NoRegister();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_UGameplayDebuggingControllerComponent();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_AGaneplayDebuggerProxyHUD_NoRegister();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_AGaneplayDebuggerProxyHUD();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_AGameplayDebuggingHUDComponent_NoRegister();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_AGameplayDebuggingHUDComponent();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientAutoActivate();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientEnableTargetSelection();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientReplicateMessage();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_OnRep_AutoActivate();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ServerReplicateMessage();
	GAMEPLAYDEBUGGER_API class UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ServerSetActorToDebug();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_AGameplayDebuggingReplicator_NoRegister();
	GAMEPLAYDEBUGGER_API class UClass* Z_Construct_UClass_AGameplayDebuggingReplicator();
	GAMEPLAYDEBUGGER_API class UPackage* Z_Construct_UPackage_GameplayDebugger();
	UScriptStruct* Z_Construct_UScriptStruct_FGDTCustomViewNames()
	{
		UPackage* Outer=Z_Construct_UPackage_GameplayDebugger();
		extern uint32 Get_Z_Construct_UScriptStruct_FGDTCustomViewNames_CRC();
		static UScriptStruct* ReturnStruct = FindExistingStructIfHotReload(Outer, TEXT("GDTCustomViewNames"), sizeof(FGDTCustomViewNames), Get_Z_Construct_UScriptStruct_FGDTCustomViewNames_CRC());
		if (!ReturnStruct)
		{
			ReturnStruct = new(EC_InternalUseOnlyConstructor, Outer, TEXT("GDTCustomViewNames"), RF_Public|RF_Transient|RF_Native) UScriptStruct(FObjectInitializer(), NULL, new UScriptStruct::TCppStructOps<FGDTCustomViewNames>, EStructFlags(0x00000001));
			UProperty* NewProp_GameView5 = new(EC_InternalUseOnlyConstructor, ReturnStruct, TEXT("GameView5"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(GameView5, FGDTCustomViewNames), 0x0000000000004001);
			UProperty* NewProp_GameView4 = new(EC_InternalUseOnlyConstructor, ReturnStruct, TEXT("GameView4"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(GameView4, FGDTCustomViewNames), 0x0000000000004001);
			UProperty* NewProp_GameView3 = new(EC_InternalUseOnlyConstructor, ReturnStruct, TEXT("GameView3"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(GameView3, FGDTCustomViewNames), 0x0000000000004001);
			UProperty* NewProp_GameView2 = new(EC_InternalUseOnlyConstructor, ReturnStruct, TEXT("GameView2"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(GameView2, FGDTCustomViewNames), 0x0000000000004001);
			UProperty* NewProp_GameView1 = new(EC_InternalUseOnlyConstructor, ReturnStruct, TEXT("GameView1"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(GameView1, FGDTCustomViewNames), 0x0000000000004001);
			ReturnStruct->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnStruct->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnStruct, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
			MetaData->SetValue(NewProp_GameView5, TEXT("Category"), TEXT("Settings"));
			MetaData->SetValue(NewProp_GameView5, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
			MetaData->SetValue(NewProp_GameView4, TEXT("Category"), TEXT("Settings"));
			MetaData->SetValue(NewProp_GameView4, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
			MetaData->SetValue(NewProp_GameView3, TEXT("Category"), TEXT("Settings"));
			MetaData->SetValue(NewProp_GameView3, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
			MetaData->SetValue(NewProp_GameView2, TEXT("Category"), TEXT("Settings"));
			MetaData->SetValue(NewProp_GameView2, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
			MetaData->SetValue(NewProp_GameView1, TEXT("Category"), TEXT("Settings"));
			MetaData->SetValue(NewProp_GameView1, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
#endif
		}
		return ReturnStruct;
	}
	uint32 Get_Z_Construct_UScriptStruct_FGDTCustomViewNames_CRC() { return 3199901738U; }
	UClass* Z_Construct_UClass_UGameplayDebuggerSettings_NoRegister()
	{
		return UGameplayDebuggerSettings::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayDebuggerSettings()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UObject();
			Z_Construct_UPackage_GameplayDebugger();
			OuterClass = UGameplayDebuggerSettings::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20100084;


PRAGMA_DISABLE_DEPRECATION_WARNINGS
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView5, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_GameView5 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView5"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView5, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(GameView5, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView4, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_GameView4 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView4"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView4, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(GameView4, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView3, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_GameView3 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView3"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView3, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(GameView3, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView2, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_GameView2 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView2"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView2, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(GameView2, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView1, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_GameView1 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView1"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView1, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(GameView1, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(Perception, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_Perception = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Perception"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(Perception, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(Perception, UGameplayDebuggerSettings), sizeof(bool), true);
				UProperty* NewProp_ActiveEQSIndex = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("ActiveEQSIndex"), RF_Public|RF_Transient|RF_Native) UIntProperty(CPP_PROPERTY_BASE(ActiveEQSIndex, UGameplayDebuggerSettings), 0x0000080000004001);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(EnableEQSOnHUD, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_EnableEQSOnHUD = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("EnableEQSOnHUD"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(EnableEQSOnHUD, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(EnableEQSOnHUD, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(EQS, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_EQS = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("EQS"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(EQS, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(EQS, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(BehaviorTree, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_BehaviorTree = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("BehaviorTree"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(BehaviorTree, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(BehaviorTree, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(Basic, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_Basic = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Basic"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(Basic, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(Basic, UGameplayDebuggerSettings), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(OverHead, UGameplayDebuggerSettings, bool);
				UProperty* NewProp_OverHead = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("OverHead"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(OverHead, UGameplayDebuggerSettings), 0x0000080000004001, CPP_BOOL_PROPERTY_BITMASK(OverHead, UGameplayDebuggerSettings), sizeof(bool), true);
				UProperty* NewProp_CustomViewNames = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CustomViewNames"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CustomViewNames, UGameplayDebuggerSettings), 0x0000080000004001, Z_Construct_UScriptStruct_FGDTCustomViewNames());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->ClassConfigName = FName(TEXT("EditorPerProjectUserSettings"));
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayDebuggerSettings.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_GameView5, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_GameView5, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_GameView4, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_GameView4, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_GameView3, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_GameView3, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_GameView2, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_GameView2, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_GameView1, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_GameView1, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_Perception, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_Perception, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_ActiveEQSIndex, TEXT("Category"), TEXT("GameplayDebugger|EQS"));
				MetaData->SetValue(NewProp_ActiveEQSIndex, TEXT("EditCondition"), TEXT("EQS"));
				MetaData->SetValue(NewProp_ActiveEQSIndex, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_EnableEQSOnHUD, TEXT("Category"), TEXT("GameplayDebugger|EQS"));
				MetaData->SetValue(NewProp_EnableEQSOnHUD, TEXT("EditCondition"), TEXT("EQS"));
				MetaData->SetValue(NewProp_EnableEQSOnHUD, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_EQS, TEXT("Category"), TEXT("GameplayDebugger|EQS"));
				MetaData->SetValue(NewProp_EQS, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_BehaviorTree, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_BehaviorTree, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_Basic, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_Basic, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_OverHead, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_OverHead, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
				MetaData->SetValue(NewProp_CustomViewNames, TEXT("Category"), TEXT("GameplayDebugger"));
				MetaData->SetValue(NewProp_CustomViewNames, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggerSettings.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayDebuggerSettings(Z_Construct_UClass_UGameplayDebuggerSettings, TEXT("UGameplayDebuggerSettings"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayDebuggerSettings);
	UEnum* Z_Construct_UEnum_GameplayDebugger_EAIDebugDrawDataView()
	{
		UPackage* Outer=Z_Construct_UPackage_GameplayDebugger();
		extern uint32 Get_Z_Construct_UEnum_GameplayDebugger_EAIDebugDrawDataView_CRC();
		static UEnum* ReturnEnum = FindExistingEnumIfHotReload(Outer, TEXT("EAIDebugDrawDataView"), 0, Get_Z_Construct_UEnum_GameplayDebugger_EAIDebugDrawDataView_CRC());
		if (!ReturnEnum)
		{
			ReturnEnum = new(EC_InternalUseOnlyConstructor, Outer, TEXT("EAIDebugDrawDataView"), RF_Public|RF_Transient|RF_Native) UEnum(FObjectInitializer());
			TArray<TPair<FName, uint8>> EnumNames;
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::Empty")), 0));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::OverHead")), 1));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::Basic")), 2));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::BehaviorTree")), 3));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::EQS")), 4));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::Perception")), 5));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::GameView1")), 6));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::GameView2")), 7));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::GameView3")), 8));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::GameView4")), 9));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::GameView5")), 10));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::NavMesh")), 11));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::MAX")), 12));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EAIDebugDrawDataView::EAIDebugDrawDataView_MAX")), 13));
			ReturnEnum->SetEnums(EnumNames, UEnum::ECppForm::Namespaced);
#if WITH_METADATA
			UMetaData* MetaData = ReturnEnum->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnEnum, TEXT("MAX.Hidden"), TEXT(""));
			MetaData->SetValue(ReturnEnum, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingTypes.h"));
#endif
		}
		return ReturnEnum;
	}
	uint32 Get_Z_Construct_UEnum_GameplayDebugger_EAIDebugDrawDataView_CRC() { return 3667925499U; }
	UEnum* Z_Construct_UEnum_GameplayDebugger_EDebugComponentMessage()
	{
		UPackage* Outer=Z_Construct_UPackage_GameplayDebugger();
		extern uint32 Get_Z_Construct_UEnum_GameplayDebugger_EDebugComponentMessage_CRC();
		static UEnum* ReturnEnum = FindExistingEnumIfHotReload(Outer, TEXT("EDebugComponentMessage"), 0, Get_Z_Construct_UEnum_GameplayDebugger_EDebugComponentMessage_CRC());
		if (!ReturnEnum)
		{
			ReturnEnum = new(EC_InternalUseOnlyConstructor, Outer, TEXT("EDebugComponentMessage"), RF_Public|RF_Transient|RF_Native) UEnum(FObjectInitializer());
			TArray<TPair<FName, uint8>> EnumNames;
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EDebugComponentMessage::EnableExtendedView")), 0));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EDebugComponentMessage::DisableExtendedView")), 1));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EDebugComponentMessage::ActivateReplication")), 2));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EDebugComponentMessage::DeactivateReplilcation")), 3));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EDebugComponentMessage::ActivateDataView")), 4));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EDebugComponentMessage::DeactivateDataView")), 5));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EDebugComponentMessage::SetMultipleDataViews")), 6));
			EnumNames.Add(TPairInitializer<FName, uint8>(FName(TEXT("EDebugComponentMessage::EDebugComponentMessage_MAX")), 7));
			ReturnEnum->SetEnums(EnumNames, UEnum::ECppForm::Namespaced);
#if WITH_METADATA
			UMetaData* MetaData = ReturnEnum->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnEnum, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
			MetaData->SetValue(ReturnEnum, TEXT("ToolTip"), TEXT("struct FEnvQueryInstance;"));
#endif
		}
		return ReturnEnum;
	}
	uint32 Get_Z_Construct_UEnum_GameplayDebugger_EDebugComponentMessage_CRC() { return 3773499734U; }
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_ClientEnableTargetSelection()
	{
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ClientEnableTargetSelection"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x81020CC0, 65535, sizeof(GameplayDebuggingComponent_eventClientEnableTargetSelection_Parms));
			CPP_BOOL_PROPERTY_BITMASK_STRUCT(bEnable, GameplayDebuggingComponent_eventClientEnableTargetSelection_Parms, bool);
			UProperty* NewProp_bEnable = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("bEnable"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bEnable, GameplayDebuggingComponent_eventClientEnableTargetSelection_Parms), 0x0000000000000080, CPP_BOOL_PROPERTY_BITMASK(bEnable, GameplayDebuggingComponent_eventClientEnableTargetSelection_Parms), sizeof(bool), true);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnCycleDetailsView()
	{
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("OnCycleDetailsView"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x00020400, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_PathCorridorData()
	{
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("OnRep_PathCorridorData"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x00020400, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateBlackboard()
	{
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("OnRep_UpdateBlackboard"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x00020400, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateEQS()
	{
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("OnRep_UpdateEQS"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x00020400, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateNavmesh()
	{
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("OnRep_UpdateNavmesh"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x00020400, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_ServerCollectNavmeshData()
	{
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ServerCollectNavmeshData"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x80220CC0, 65535, sizeof(GameplayDebuggingComponent_eventServerCollectNavmeshData_Parms));
			UProperty* NewProp_TargetLocation = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("TargetLocation"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(TargetLocation, GameplayDebuggingComponent_eventServerCollectNavmeshData_Parms), 0x0000000000000080, Z_Construct_UScriptStruct_FVector_NetQuantize10());
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_ServerDiscardNavmeshData()
	{
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ServerDiscardNavmeshData"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x80220CC0, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_UGameplayDebuggingComponent_ServerReplicateData()
	{
		struct GameplayDebuggingComponent_eventServerReplicateData_Parms
		{
			uint32 InMessage;
			uint32 DataView;
		};
		UObject* Outer=Z_Construct_UClass_UGameplayDebuggingComponent();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ServerReplicateData"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x00020601, 65535, sizeof(GameplayDebuggingComponent_eventServerReplicateData_Parms));
			UProperty* NewProp_DataView = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("DataView"), RF_Public|RF_Transient|RF_Native) UUInt32Property(CPP_PROPERTY_BASE(DataView, GameplayDebuggingComponent_eventServerReplicateData_Parms), 0x0000000000000080);
			UProperty* NewProp_InMessage = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("InMessage"), RF_Public|RF_Transient|RF_Native) UUInt32Property(CPP_PROPERTY_BASE(InMessage, GameplayDebuggingComponent_eventServerReplicateData_Parms), 0x0000000000000080);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
		}
		return ReturnFunction;
	}
	UClass* Z_Construct_UClass_UGameplayDebuggingComponent_NoRegister()
	{
		return UGameplayDebuggingComponent::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayDebuggingComponent()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UPrimitiveComponent();
			Z_Construct_UPackage_GameplayDebugger();
			OuterClass = UGameplayDebuggingComponent::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20B00084;

				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_ClientEnableTargetSelection());
				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_OnCycleDetailsView());
				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_PathCorridorData());
				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateBlackboard());
				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateEQS());
				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateNavmesh());
				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_ServerCollectNavmeshData());
				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_ServerDiscardNavmeshData());
				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayDebuggingComponent_ServerReplicateData());

PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_TargetActor = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("TargetActor"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(TargetActor, UGameplayDebuggingComponent), 0x0000000000000020, Z_Construct_UClass_AActor_NoRegister());
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(bIsUsingAbilities, UGameplayDebuggingComponent, uint8);
				UProperty* NewProp_bIsUsingAbilities = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("bIsUsingAbilities"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bIsUsingAbilities, UGameplayDebuggingComponent), 0x0000000000000020, CPP_BOOL_PROPERTY_BITMASK(bIsUsingAbilities, UGameplayDebuggingComponent), sizeof(uint8), false);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(bIsUsingBehaviorTree, UGameplayDebuggingComponent, uint8);
				UProperty* NewProp_bIsUsingBehaviorTree = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("bIsUsingBehaviorTree"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bIsUsingBehaviorTree, UGameplayDebuggingComponent), 0x0000000000000020, CPP_BOOL_PROPERTY_BITMASK(bIsUsingBehaviorTree, UGameplayDebuggingComponent), sizeof(uint8), false);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(bIsUsingCharacter, UGameplayDebuggingComponent, uint8);
				UProperty* NewProp_bIsUsingCharacter = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("bIsUsingCharacter"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bIsUsingCharacter, UGameplayDebuggingComponent), 0x0000000000000020, CPP_BOOL_PROPERTY_BITMASK(bIsUsingCharacter, UGameplayDebuggingComponent), sizeof(uint8), false);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(bIsUsingPathFollowing, UGameplayDebuggingComponent, uint8);
				UProperty* NewProp_bIsUsingPathFollowing = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("bIsUsingPathFollowing"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bIsUsingPathFollowing, UGameplayDebuggingComponent), 0x0000000000000020, CPP_BOOL_PROPERTY_BITMASK(bIsUsingPathFollowing, UGameplayDebuggingComponent), sizeof(uint8), false);
				UProperty* NewProp_NextPathPointIndex = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("NextPathPointIndex"), RF_Public|RF_Transient|RF_Native) UIntProperty(CPP_PROPERTY_BASE(NextPathPointIndex, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_SensingComponentLocation = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("SensingComponentLocation"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(SensingComponentLocation, UGameplayDebuggingComponent), 0x0000000000000020, Z_Construct_UScriptStruct_FVector());
				UProperty* NewProp_EQSRepData = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("EQSRepData"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(EQSRepData, UGameplayDebuggingComponent), 0x0000000100000020);
				NewProp_EQSRepData->RepNotifyFunc = FName(TEXT("OnRep_UpdateEQS"));
				UProperty* NewProp_EQSRepData_Inner = new(EC_InternalUseOnlyConstructor, NewProp_EQSRepData, TEXT("EQSRepData"), RF_Public|RF_Transient|RF_Native) UByteProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000);
				UProperty* NewProp_NavmeshRepData = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("NavmeshRepData"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(NavmeshRepData, UGameplayDebuggingComponent), 0x0000000100000020);
				NewProp_NavmeshRepData->RepNotifyFunc = FName(TEXT("OnRep_UpdateNavmesh"));
				UProperty* NewProp_NavmeshRepData_Inner = new(EC_InternalUseOnlyConstructor, NewProp_NavmeshRepData, TEXT("NavmeshRepData"), RF_Public|RF_Transient|RF_Native) UByteProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000);
				UProperty* NewProp_PathCorridorData = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PathCorridorData"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(PathCorridorData, UGameplayDebuggingComponent), 0x0000000100000020);
				NewProp_PathCorridorData->RepNotifyFunc = FName(TEXT("OnRep_PathCorridorData"));
				UProperty* NewProp_PathCorridorData_Inner = new(EC_InternalUseOnlyConstructor, NewProp_PathCorridorData, TEXT("PathCorridorData"), RF_Public|RF_Transient|RF_Native) UByteProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000);
				UProperty* NewProp_PathPoints = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PathPoints"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(PathPoints, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_PathPoints_Inner = new(EC_InternalUseOnlyConstructor, NewProp_PathPoints, TEXT("PathPoints"), RF_Public|RF_Transient|RF_Native) UStructProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000, Z_Construct_UScriptStruct_FVector());
				UProperty* NewProp_BlackboardRepData = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("BlackboardRepData"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(BlackboardRepData, UGameplayDebuggingComponent), 0x0000000100000020);
				NewProp_BlackboardRepData->RepNotifyFunc = FName(TEXT("OnRep_UpdateBlackboard"));
				UProperty* NewProp_BlackboardRepData_Inner = new(EC_InternalUseOnlyConstructor, NewProp_BlackboardRepData, TEXT("BlackboardRepData"), RF_Public|RF_Transient|RF_Native) UByteProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000);
				UProperty* NewProp_BrainComponentString = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("BrainComponentString"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(BrainComponentString, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_BrainComponentName = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("BrainComponentName"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(BrainComponentName, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_MontageInfo = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("MontageInfo"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(MontageInfo, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_AbilityInfo = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("AbilityInfo"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(AbilityInfo, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_NavDataInfo = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("NavDataInfo"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(NavDataInfo, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_GameplayTasksState = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameplayTasksState"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(GameplayTasksState, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_CurrentAIAssets = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CurrentAIAssets"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(CurrentAIAssets, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_CurrentAIState = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CurrentAIState"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(CurrentAIState, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_CurrentAITask = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CurrentAITask"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(CurrentAITask, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_PathFollowingInfo = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PathFollowingInfo"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(PathFollowingInfo, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_MovementModeInfo = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("MovementModeInfo"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(MovementModeInfo, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_MovementBaseInfo = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("MovementBaseInfo"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(MovementBaseInfo, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_DebugIcon = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugIcon"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(DebugIcon, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_PawnClass = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PawnClass"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(PawnClass, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_PawnName = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PawnName"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(PawnName, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_ControllerName = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("ControllerName"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(ControllerName, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_ReplicateViewDataCounters = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("ReplicateViewDataCounters"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(ReplicateViewDataCounters, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_ReplicateViewDataCounters_Inner = new(EC_InternalUseOnlyConstructor, NewProp_ReplicateViewDataCounters, TEXT("ReplicateViewDataCounters"), RF_Public|RF_Transient|RF_Native) UIntProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000);
				UProperty* NewProp_ShowExtendedInformatiomCounter = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("ShowExtendedInformatiomCounter"), RF_Public|RF_Transient|RF_Native) UIntProperty(CPP_PROPERTY_BASE(ShowExtendedInformatiomCounter, UGameplayDebuggingComponent), 0x0000000000000020);
				UProperty* NewProp_DebugComponentClassName = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugComponentClassName"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(DebugComponentClassName, UGameplayDebuggingComponent), 0x0000000000044000);
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_ClientEnableTargetSelection()); // 33722826
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_OnCycleDetailsView()); // 3788199373
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_PathCorridorData()); // 654978181
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateBlackboard()); // 177016569
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateEQS()); // 540184030
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_OnRep_UpdateNavmesh()); // 1350464706
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_ServerCollectNavmeshData()); // 653782587
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_ServerDiscardNavmeshData()); // 1659576381
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayDebuggingComponent_ServerReplicateData()); // 1395397690
				OuterClass->ClassConfigName = FName(TEXT("Engine"));
				OuterClass->Interfaces.Add(FImplementedInterface(Z_Construct_UClass_UEQSQueryResultSourceInterface_NoRegister(), VTABLE_OFFSET(UGameplayDebuggingComponent, IEQSQueryResultSourceInterface), false ));
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("HideCategories"), TEXT("Mobility Trigger ComponentReplication"));
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayDebuggingComponent.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_TargetActor, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_TargetActor, TEXT("ToolTip"), TEXT("controller related stuff"));
				MetaData->SetValue(NewProp_bIsUsingAbilities, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_bIsUsingBehaviorTree, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_bIsUsingCharacter, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_bIsUsingPathFollowing, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_NextPathPointIndex, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_SensingComponentLocation, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_SensingComponentLocation, TEXT("ToolTip"), TEXT("End EQS replication data"));
				MetaData->SetValue(NewProp_EQSRepData, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_EQSRepData, TEXT("ToolTip"), TEXT("Begin EQS replication data"));
				MetaData->SetValue(NewProp_NavmeshRepData, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_NavmeshRepData, TEXT("ToolTip"), TEXT("End path replication data"));
				MetaData->SetValue(NewProp_PathCorridorData, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_PathPoints, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_PathPoints, TEXT("ToolTip"), TEXT("Begin path replication data"));
				MetaData->SetValue(NewProp_BlackboardRepData, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_BrainComponentString, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_BrainComponentName, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_MontageInfo, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_AbilityInfo, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_NavDataInfo, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_GameplayTasksState, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_CurrentAIAssets, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_CurrentAIState, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_CurrentAITask, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_PathFollowingInfo, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_MovementModeInfo, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_MovementBaseInfo, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_DebugIcon, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_PawnClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_PawnName, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_ControllerName, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_ReplicateViewDataCounters, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_ShowExtendedInformatiomCounter, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
				MetaData->SetValue(NewProp_DebugComponentClassName, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingComponent.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayDebuggingComponent(Z_Construct_UClass_UGameplayDebuggingComponent, TEXT("UGameplayDebuggingComponent"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayDebuggingComponent);
	UClass* Z_Construct_UClass_UGameplayDebuggingControllerComponent_NoRegister()
	{
		return UGameplayDebuggingControllerComponent::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayDebuggingControllerComponent()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UActorComponent();
			Z_Construct_UPackage_GameplayDebugger();
			OuterClass = UGameplayDebuggingControllerComponent::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20B00084;


PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_GameHUDBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameHUDBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(GameHUDBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_OnScreenDebugMessagesBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("OnScreenDebugMessagesBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(OnScreenDebugMessagesBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_DebugCameraBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugCameraBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(DebugCameraBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CycleDetailsViewBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CycleDetailsViewBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CycleDetailsViewBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategoryNineBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategoryNineBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategoryNineBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategoryEightBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategoryEightBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategoryEightBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategorySevenBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategorySevenBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategorySevenBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategorySixBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategorySixBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategorySixBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategoryFiveBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategoryFiveBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategoryFiveBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategoryFourBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategoryFourBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategoryFourBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategoryThreeBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategoryThreeBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategoryThreeBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategoryTwoBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategoryTwoBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategoryTwoBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategoryOneBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategoryOneBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategoryOneBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_CategoryZeroBind = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("CategoryZeroBind"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(CategoryZeroBind, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_ActivationKey = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("ActivationKey"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(ActivationKey, UGameplayDebuggingControllerComponent), 0x0000000000004000, Z_Construct_UScriptStruct_FInputChord());
				UProperty* NewProp_DebugCameraInputComponent = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugCameraInputComponent"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(DebugCameraInputComponent, UGameplayDebuggingControllerComponent), 0x0000080000082008, Z_Construct_UClass_UInputComponent_NoRegister());
				UProperty* NewProp_AIDebugViewInputComponent = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("AIDebugViewInputComponent"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(AIDebugViewInputComponent, UGameplayDebuggingControllerComponent), 0x0000080000082008, Z_Construct_UClass_UInputComponent_NoRegister());
				UProperty* NewProp_DebugAITargetActor = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugAITargetActor"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(DebugAITargetActor, UGameplayDebuggingControllerComponent), 0x0000080000002000, Z_Construct_UClass_AActor_NoRegister());
				UProperty* NewProp_OnDebugAIHUD = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("OnDebugAIHUD"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(OnDebugAIHUD, UGameplayDebuggingControllerComponent), 0x0000080000002000, Z_Construct_UClass_AGameplayDebuggingHUDComponent_NoRegister());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->ClassConfigName = FName(TEXT("Engine"));
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("HideCategories"), TEXT("ComponentReplication"));
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_GameHUDBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_OnScreenDebugMessagesBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_DebugCameraBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CycleDetailsViewBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategoryNineBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategoryEightBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategorySevenBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategorySixBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategoryFiveBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategoryFourBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategoryThreeBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategoryTwoBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategoryOneBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_CategoryZeroBind, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_ActivationKey, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_DebugCameraInputComponent, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_DebugCameraInputComponent, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_AIDebugViewInputComponent, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_AIDebugViewInputComponent, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_DebugAITargetActor, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(NewProp_OnDebugAIHUD, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayDebuggingControllerComponent(Z_Construct_UClass_UGameplayDebuggingControllerComponent, TEXT("UGameplayDebuggingControllerComponent"));
	UClass* Z_Construct_UClass_AGaneplayDebuggerProxyHUD_NoRegister()
	{
		return AGaneplayDebuggerProxyHUD::StaticClass();
	}
	UClass* Z_Construct_UClass_AGaneplayDebuggerProxyHUD()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AHUD();
			Z_Construct_UPackage_GameplayDebugger();
			OuterClass = AGaneplayDebuggerProxyHUD::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x2080028C;


				OuterClass->ClassConfigName = FName(TEXT("Game"));
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("HideCategories"), TEXT("Rendering Actor Input Replication"));
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingControllerComponent.h"));
				MetaData->SetValue(OuterClass, TEXT("ShowCategories"), TEXT("Input|MouseInput Input|TouchInput"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AGaneplayDebuggerProxyHUD(Z_Construct_UClass_AGaneplayDebuggerProxyHUD, TEXT("AGaneplayDebuggerProxyHUD"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(AGaneplayDebuggerProxyHUD);
	UClass* Z_Construct_UClass_AGameplayDebuggingHUDComponent_NoRegister()
	{
		return AGameplayDebuggingHUDComponent::StaticClass();
	}
	UClass* Z_Construct_UClass_AGameplayDebuggingHUDComponent()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AActor();
			Z_Construct_UPackage_GameplayDebugger();
			OuterClass = AGameplayDebuggingHUDComponent::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20900284;


PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_PlayerOwner = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PlayerOwner"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(PlayerOwner, AGameplayDebuggingHUDComponent), 0x0000080000002000, Z_Construct_UClass_APlayerController_NoRegister());
				UProperty* NewProp_Canvas = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Canvas"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(Canvas, AGameplayDebuggingHUDComponent), 0x0000080000002000, Z_Construct_UClass_UCanvas_NoRegister());
				UProperty* NewProp_DebugInfoStartY = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugInfoStartY"), RF_Public|RF_Transient|RF_Native) UFloatProperty(CPP_PROPERTY_BASE(DebugInfoStartY, AGameplayDebuggingHUDComponent), 0x0000000000004000);
				UProperty* NewProp_DebugInfoStartX = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugInfoStartX"), RF_Public|RF_Transient|RF_Native) UFloatProperty(CPP_PROPERTY_BASE(DebugInfoStartX, AGameplayDebuggingHUDComponent), 0x0000000000004000);
				UProperty* NewProp_MenuStartY = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("MenuStartY"), RF_Public|RF_Transient|RF_Native) UFloatProperty(CPP_PROPERTY_BASE(MenuStartY, AGameplayDebuggingHUDComponent), 0x0000000000004000);
				UProperty* NewProp_MenuStartX = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("MenuStartX"), RF_Public|RF_Transient|RF_Native) UFloatProperty(CPP_PROPERTY_BASE(MenuStartX, AGameplayDebuggingHUDComponent), 0x0000000000004000);
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->ClassConfigName = FName(TEXT("Engine"));
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayDebuggingHUDComponent.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingHUDComponent.h"));
				MetaData->SetValue(NewProp_PlayerOwner, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingHUDComponent.h"));
				MetaData->SetValue(NewProp_Canvas, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingHUDComponent.h"));
				MetaData->SetValue(NewProp_DebugInfoStartY, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingHUDComponent.h"));
				MetaData->SetValue(NewProp_DebugInfoStartX, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingHUDComponent.h"));
				MetaData->SetValue(NewProp_MenuStartY, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingHUDComponent.h"));
				MetaData->SetValue(NewProp_MenuStartX, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingHUDComponent.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AGameplayDebuggingHUDComponent(Z_Construct_UClass_AGameplayDebuggingHUDComponent, TEXT("AGameplayDebuggingHUDComponent"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(AGameplayDebuggingHUDComponent);
	UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientAutoActivate()
	{
		UObject* Outer=Z_Construct_UClass_AGameplayDebuggingReplicator();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ClientAutoActivate"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x01020CC0, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientEnableTargetSelection()
	{
		UObject* Outer=Z_Construct_UClass_AGameplayDebuggingReplicator();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ClientEnableTargetSelection"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x81020CC0, 65535, sizeof(GameplayDebuggingReplicator_eventClientEnableTargetSelection_Parms));
			UProperty* NewProp_Context = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("Context"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(Context, GameplayDebuggingReplicator_eventClientEnableTargetSelection_Parms), 0x0000000000000080, Z_Construct_UClass_APlayerController_NoRegister());
			CPP_BOOL_PROPERTY_BITMASK_STRUCT(bEnable, GameplayDebuggingReplicator_eventClientEnableTargetSelection_Parms, bool);
			UProperty* NewProp_bEnable = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("bEnable"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bEnable, GameplayDebuggingReplicator_eventClientEnableTargetSelection_Parms), 0x0000000000000080, CPP_BOOL_PROPERTY_BITMASK(bEnable, GameplayDebuggingReplicator_eventClientEnableTargetSelection_Parms), sizeof(bool), true);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientReplicateMessage()
	{
		UObject* Outer=Z_Construct_UClass_AGameplayDebuggingReplicator();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ClientReplicateMessage"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x81020CC0, 65535, sizeof(GameplayDebuggingReplicator_eventClientReplicateMessage_Parms));
			UProperty* NewProp_DataView = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("DataView"), RF_Public|RF_Transient|RF_Native) UUInt32Property(CPP_PROPERTY_BASE(DataView, GameplayDebuggingReplicator_eventClientReplicateMessage_Parms), 0x0000000000000080);
			UProperty* NewProp_InMessage = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("InMessage"), RF_Public|RF_Transient|RF_Native) UUInt32Property(CPP_PROPERTY_BASE(InMessage, GameplayDebuggingReplicator_eventClientReplicateMessage_Parms), 0x0000000000000080);
			UProperty* NewProp_Actor = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("Actor"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(Actor, GameplayDebuggingReplicator_eventClientReplicateMessage_Parms), 0x0000000000000080, Z_Construct_UClass_AActor_NoRegister());
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_OnRep_AutoActivate()
	{
		UObject* Outer=Z_Construct_UClass_AGameplayDebuggingReplicator();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("OnRep_AutoActivate"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x00020400, 65535);
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ServerReplicateMessage()
	{
		UObject* Outer=Z_Construct_UClass_AGameplayDebuggingReplicator();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ServerReplicateMessage"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x80220CC0, 65535, sizeof(GameplayDebuggingReplicator_eventServerReplicateMessage_Parms));
			UProperty* NewProp_DataView = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("DataView"), RF_Public|RF_Transient|RF_Native) UUInt32Property(CPP_PROPERTY_BASE(DataView, GameplayDebuggingReplicator_eventServerReplicateMessage_Parms), 0x0000000000000080);
			UProperty* NewProp_InMessage = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("InMessage"), RF_Public|RF_Transient|RF_Native) UUInt32Property(CPP_PROPERTY_BASE(InMessage, GameplayDebuggingReplicator_eventServerReplicateMessage_Parms), 0x0000000000000080);
			UProperty* NewProp_Actor = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("Actor"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(Actor, GameplayDebuggingReplicator_eventServerReplicateMessage_Parms), 0x0000000000000080, Z_Construct_UClass_AActor_NoRegister());
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
#endif
		}
		return ReturnFunction;
	}
	UFunction* Z_Construct_UFunction_AGameplayDebuggingReplicator_ServerSetActorToDebug()
	{
		UObject* Outer=Z_Construct_UClass_AGameplayDebuggingReplicator();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("ServerSetActorToDebug"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x80220CC0, 65535, sizeof(GameplayDebuggingReplicator_eventServerSetActorToDebug_Parms));
			UProperty* NewProp_InActor = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("InActor"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(InActor, GameplayDebuggingReplicator_eventServerSetActorToDebug_Parms), 0x0000000000000080, Z_Construct_UClass_AActor_NoRegister());
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
#endif
		}
		return ReturnFunction;
	}
	UClass* Z_Construct_UClass_AGameplayDebuggingReplicator_NoRegister()
	{
		return AGameplayDebuggingReplicator::StaticClass();
	}
	UClass* Z_Construct_UClass_AGameplayDebuggingReplicator()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_AActor();
			Z_Construct_UPackage_GameplayDebugger();
			OuterClass = AGameplayDebuggingReplicator::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x2090028C;

				OuterClass->LinkChild(Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientAutoActivate());
				OuterClass->LinkChild(Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientEnableTargetSelection());
				OuterClass->LinkChild(Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientReplicateMessage());
				OuterClass->LinkChild(Z_Construct_UFunction_AGameplayDebuggingReplicator_OnRep_AutoActivate());
				OuterClass->LinkChild(Z_Construct_UFunction_AGameplayDebuggingReplicator_ServerReplicateMessage());
				OuterClass->LinkChild(Z_Construct_UFunction_AGameplayDebuggingReplicator_ServerSetActorToDebug());

PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_DefaultTexture_Green = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DefaultTexture_Green"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(DefaultTexture_Green, AGameplayDebuggingReplicator), 0x0000000000000000, Z_Construct_UClass_UTexture2D_NoRegister());
				UProperty* NewProp_DefaultTexture_Red = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DefaultTexture_Red"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(DefaultTexture_Red, AGameplayDebuggingReplicator), 0x0000000000000000, Z_Construct_UClass_UTexture2D_NoRegister());
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView5, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_GameView5 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView5"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView5, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(GameView5, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView4, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_GameView4 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView4"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView4, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(GameView4, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView3, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_GameView3 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView3"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView3, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(GameView3, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView2, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_GameView2 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView2"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView2, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(GameView2, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(GameView1, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_GameView1 = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("GameView1"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(GameView1, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(GameView1, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(Perception, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_Perception = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Perception"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(Perception, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(Perception, AGameplayDebuggingReplicator), sizeof(bool), true);
				UProperty* NewProp_ActiveEQSIndex = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("ActiveEQSIndex"), RF_Public|RF_Transient|RF_Native) UIntProperty(CPP_PROPERTY_BASE(ActiveEQSIndex, AGameplayDebuggingReplicator), 0x0000000000002001);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(EnableEQSOnHUD, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_EnableEQSOnHUD = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("EnableEQSOnHUD"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(EnableEQSOnHUD, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(EnableEQSOnHUD, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(EQS, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_EQS = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("EQS"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(EQS, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(EQS, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(BehaviorTree, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_BehaviorTree = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("BehaviorTree"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(BehaviorTree, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(BehaviorTree, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(Basic, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_Basic = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("Basic"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(Basic, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(Basic, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(OverHead, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_OverHead = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("OverHead"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(OverHead, AGameplayDebuggingReplicator), 0x0000000000002001, CPP_BOOL_PROPERTY_BITMASK(OverHead, AGameplayDebuggingReplicator), sizeof(bool), true);
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(bAutoActivate, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_bAutoActivate = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("bAutoActivate"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bAutoActivate, AGameplayDebuggingReplicator), 0x0000000100002020, CPP_BOOL_PROPERTY_BITMASK(bAutoActivate, AGameplayDebuggingReplicator), sizeof(bool), true);
				NewProp_bAutoActivate->RepNotifyFunc = FName(TEXT("OnRep_AutoActivate"));
				CPP_BOOL_PROPERTY_BITMASK_STRUCT(bIsGlobalInWorld, AGameplayDebuggingReplicator, bool);
				UProperty* NewProp_bIsGlobalInWorld = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("bIsGlobalInWorld"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(bIsGlobalInWorld, AGameplayDebuggingReplicator), 0x0000000000002020, CPP_BOOL_PROPERTY_BITMASK(bIsGlobalInWorld, AGameplayDebuggingReplicator), sizeof(bool), true);
				UProperty* NewProp_LastSelectedActorToDebug = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("LastSelectedActorToDebug"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(LastSelectedActorToDebug, AGameplayDebuggingReplicator), 0x0000000000002020, Z_Construct_UClass_AActor_NoRegister());
				UProperty* NewProp_LocalPlayerOwner = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("LocalPlayerOwner"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(LocalPlayerOwner, AGameplayDebuggingReplicator), 0x0000000000002020, Z_Construct_UClass_APlayerController_NoRegister());
				UProperty* NewProp_DebugComponent = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugComponent"), RF_Public|RF_Transient|RF_Native) UObjectProperty(CPP_PROPERTY_BASE(DebugComponent, AGameplayDebuggingReplicator), 0x0000000000082028, Z_Construct_UClass_UGameplayDebuggingComponent_NoRegister());
				UProperty* NewProp_MaxEQSQueries = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("MaxEQSQueries"), RF_Public|RF_Transient|RF_Native) UIntProperty(CPP_PROPERTY_BASE(MaxEQSQueries, AGameplayDebuggingReplicator), 0x0000000000004000);
				UProperty* NewProp_DebugComponentControllerClassName = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugComponentControllerClassName"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(DebugComponentControllerClassName, AGameplayDebuggingReplicator), 0x0000000000004000);
				UProperty* NewProp_DebugComponentHUDClassName = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugComponentHUDClassName"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(DebugComponentHUDClassName, AGameplayDebuggingReplicator), 0x0000000000004000);
				UProperty* NewProp_DebugComponentClassName = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("DebugComponentClassName"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(DebugComponentClassName, AGameplayDebuggingReplicator), 0x0000000000004000);
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientAutoActivate()); // 2247596095
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientEnableTargetSelection()); // 3715290737
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_AGameplayDebuggingReplicator_ClientReplicateMessage()); // 1254183279
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_AGameplayDebuggingReplicator_OnRep_AutoActivate()); // 1657411479
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_AGameplayDebuggingReplicator_ServerReplicateMessage()); // 4233852109
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_AGameplayDebuggingReplicator_ServerSetActorToDebug()); // 4077132014
				OuterClass->ClassConfigName = FName(TEXT("Engine"));
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("HideCategories"), TEXT("Actor"));
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayDebuggingReplicator.h"));
				MetaData->SetValue(OuterClass, TEXT("IsBlueprintBase"), TEXT("false"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_DefaultTexture_Green, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_DefaultTexture_Red, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_GameView5, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_GameView5, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_GameView4, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_GameView4, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_GameView3, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_GameView3, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_GameView2, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_GameView2, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_GameView1, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_GameView1, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_Perception, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_Perception, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_ActiveEQSIndex, TEXT("Category"), TEXT("DataView|EQS"));
				MetaData->SetValue(NewProp_ActiveEQSIndex, TEXT("EditCondition"), TEXT("EQS"));
				MetaData->SetValue(NewProp_ActiveEQSIndex, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_EnableEQSOnHUD, TEXT("Category"), TEXT("DataView|EQS"));
				MetaData->SetValue(NewProp_EnableEQSOnHUD, TEXT("EditCondition"), TEXT("EQS"));
				MetaData->SetValue(NewProp_EnableEQSOnHUD, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_EQS, TEXT("Category"), TEXT("DataView|EQS"));
				MetaData->SetValue(NewProp_EQS, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_BehaviorTree, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_BehaviorTree, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_Basic, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_Basic, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_OverHead, TEXT("Category"), TEXT("DataView"));
				MetaData->SetValue(NewProp_OverHead, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_bAutoActivate, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_bIsGlobalInWorld, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_LastSelectedActorToDebug, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_LocalPlayerOwner, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_DebugComponent, TEXT("EditInline"), TEXT("true"));
				MetaData->SetValue(NewProp_DebugComponent, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_MaxEQSQueries, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_DebugComponentControllerClassName, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_DebugComponentHUDClassName, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
				MetaData->SetValue(NewProp_DebugComponentClassName, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayDebuggingReplicator.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_AGameplayDebuggingReplicator(Z_Construct_UClass_AGameplayDebuggingReplicator, TEXT("AGameplayDebuggingReplicator"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(AGameplayDebuggingReplicator);
	UPackage* Z_Construct_UPackage_GameplayDebugger()
	{
		static UPackage* ReturnPackage = NULL;
		if (!ReturnPackage)
		{
			ReturnPackage = CastChecked<UPackage>(StaticFindObjectFast(UPackage::StaticClass(), NULL, FName(TEXT("/Script/GameplayDebugger")), false, false));
			ReturnPackage->SetPackageFlags(PKG_CompiledIn | 0x00000000);
			FGuid Guid;
			Guid.A = 0xB024F293;
			Guid.B = 0x4CDDE8D6;
			Guid.C = 0x00000000;
			Guid.D = 0x00000000;
			ReturnPackage->SetGuid(Guid);

		}
		return ReturnPackage;
	}
#endif

PRAGMA_ENABLE_DEPRECATION_WARNINGS
