// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef SLATECORE_CompositeFont_generated_h
#error "CompositeFont.generated.h already included, missing '#pragma once' in CompositeFont.h"
#endif
#define SLATECORE_CompositeFont_generated_h

#define Engine_Source_Runtime_SlateCore_Public_Fonts_CompositeFont_h_158_GENERATED_BODY \
	friend SLATECORE_API class UScriptStruct* Z_Construct_UScriptStruct_FCompositeFont(); \
	static class UScriptStruct* StaticStruct();


#define Engine_Source_Runtime_SlateCore_Public_Fonts_CompositeFont_h_126_GENERATED_BODY \
	friend SLATECORE_API class UScriptStruct* Z_Construct_UScriptStruct_FCompositeSubFont(); \
	static class UScriptStruct* StaticStruct();


#define Engine_Source_Runtime_SlateCore_Public_Fonts_CompositeFont_h_98_GENERATED_BODY \
	friend SLATECORE_API class UScriptStruct* Z_Construct_UScriptStruct_FTypeface(); \
	static class UScriptStruct* StaticStruct();


#define Engine_Source_Runtime_SlateCore_Public_Fonts_CompositeFont_h_65_GENERATED_BODY \
	friend SLATECORE_API class UScriptStruct* Z_Construct_UScriptStruct_FTypefaceEntry(); \
	static class UScriptStruct* StaticStruct();


#define Engine_Source_Runtime_SlateCore_Public_Fonts_CompositeFont_h_27_GENERATED_BODY \
	friend SLATECORE_API class UScriptStruct* Z_Construct_UScriptStruct_FFontData(); \
	static class UScriptStruct* StaticStruct();


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_SlateCore_Public_Fonts_CompositeFont_h


#define FOREACH_ENUM_EFONTHINTING(op) \
	op(EFontHinting::Default) \
	op(EFontHinting::Auto) \
	op(EFontHinting::AutoLight) \
	op(EFontHinting::Monochrome) \
	op(EFontHinting::None) 
PRAGMA_ENABLE_DEPRECATION_WARNINGS
