// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef SLATECORE_Geometry_generated_h
#error "Geometry.generated.h already included, missing '#pragma once' in Geometry.h"
#endif
#define SLATECORE_Geometry_generated_h

#define Engine_Source_Runtime_SlateCore_Public_Layout_Geometry_h_26_GENERATED_BODY \
	friend SLATECORE_API class UScriptStruct* Z_Construct_UScriptStruct_FGeometry(); \
	static class UScriptStruct* StaticStruct();


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_SlateCore_Public_Layout_Geometry_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
