// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef ENGINE_AnimNode_LayeredBoneBlend_generated_h
#error "AnimNode_LayeredBoneBlend.generated.h already included, missing '#pragma once' in AnimNode_LayeredBoneBlend.h"
#endif
#define ENGINE_AnimNode_LayeredBoneBlend_generated_h

#define Engine_Source_Runtime_Engine_Classes_Animation_AnimNode_LayeredBoneBlend_h_15_GENERATED_BODY \
	friend ENGINE_API class UScriptStruct* Z_Construct_UScriptStruct_FAnimNode_LayeredBoneBlend(); \
	static class UScriptStruct* StaticStruct();


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Engine_Classes_Animation_AnimNode_LayeredBoneBlend_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
