// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
class AActor;
#ifdef ENGINE_ChildActorComponent_generated_h
#error "ChildActorComponent.generated.h already included, missing '#pragma once' in ChildActorComponent.h"
#endif
#define ENGINE_ChildActorComponent_generated_h

#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_RPC_WRAPPERS \
 \
	DECLARE_FUNCTION(execSetChildActorClass) \
	{ \
		P_GET_OBJECT(UClass,Z_Param_InClass); \
		P_FINISH; \
		this->SetChildActorClass(Z_Param_InClass); \
	}


#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_RPC_WRAPPERS_NO_PURE_DECLS \
 \
	DECLARE_FUNCTION(execSetChildActorClass) \
	{ \
		P_GET_OBJECT(UClass,Z_Param_InClass); \
		P_FINISH; \
		this->SetChildActorClass(Z_Param_InClass); \
	}


#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUChildActorComponent(); \
	friend ENGINE_API class UClass* Z_Construct_UClass_UChildActorComponent(); \
	public: \
	DECLARE_CLASS(UChildActorComponent, USceneComponent, COMPILED_IN_FLAGS(0), 0, Engine, ENGINE_API) \
	DECLARE_SERIALIZER(UChildActorComponent) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UChildActorComponent*>(this); }


#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_INCLASS \
	private: \
	static void StaticRegisterNativesUChildActorComponent(); \
	friend ENGINE_API class UClass* Z_Construct_UClass_UChildActorComponent(); \
	public: \
	DECLARE_CLASS(UChildActorComponent, USceneComponent, COMPILED_IN_FLAGS(0), 0, Engine, ENGINE_API) \
	DECLARE_SERIALIZER(UChildActorComponent) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UChildActorComponent*>(this); }


#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ENGINE_API UChildActorComponent(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UChildActorComponent) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ENGINE_API, UChildActorComponent); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UChildActorComponent); \
private: \
	/** Private copy-constructor, should never be used */ \
	ENGINE_API UChildActorComponent(const UChildActorComponent& InCopy); \
public:


#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ENGINE_API UChildActorComponent(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	ENGINE_API UChildActorComponent(const UChildActorComponent& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ENGINE_API, UChildActorComponent); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UChildActorComponent); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UChildActorComponent)


#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_11_PROLOG
#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_RPC_WRAPPERS \
	Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_INCLASS \
	Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h_14_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class ChildActorComponent."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Engine_Classes_Components_ChildActorComponent_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
