// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef ENGINE_InputAxisDelegateBinding_generated_h
#error "InputAxisDelegateBinding.generated.h already included, missing '#pragma once' in InputAxisDelegateBinding.h"
#endif
#define ENGINE_InputAxisDelegateBinding_generated_h

#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_10_GENERATED_BODY \
	friend ENGINE_API class UScriptStruct* Z_Construct_UScriptStruct_FBlueprintInputAxisDelegateBinding(); \
	static class UScriptStruct* StaticStruct();


#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_RPC_WRAPPERS
#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUInputAxisDelegateBinding(); \
	friend ENGINE_API class UClass* Z_Construct_UClass_UInputAxisDelegateBinding(); \
	public: \
	DECLARE_CLASS(UInputAxisDelegateBinding, UInputDelegateBinding, COMPILED_IN_FLAGS(0), 0, Engine, NO_API) \
	DECLARE_SERIALIZER(UInputAxisDelegateBinding) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UInputAxisDelegateBinding*>(this); }


#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_INCLASS \
	private: \
	static void StaticRegisterNativesUInputAxisDelegateBinding(); \
	friend ENGINE_API class UClass* Z_Construct_UClass_UInputAxisDelegateBinding(); \
	public: \
	DECLARE_CLASS(UInputAxisDelegateBinding, UInputDelegateBinding, COMPILED_IN_FLAGS(0), 0, Engine, NO_API) \
	DECLARE_SERIALIZER(UInputAxisDelegateBinding) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UInputAxisDelegateBinding*>(this); }


#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UInputAxisDelegateBinding(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UInputAxisDelegateBinding) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UInputAxisDelegateBinding); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UInputAxisDelegateBinding); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UInputAxisDelegateBinding(const UInputAxisDelegateBinding& InCopy); \
public:


#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UInputAxisDelegateBinding(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UInputAxisDelegateBinding(const UInputAxisDelegateBinding& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UInputAxisDelegateBinding); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UInputAxisDelegateBinding); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UInputAxisDelegateBinding)


#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_26_PROLOG
#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_RPC_WRAPPERS \
	Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_INCLASS \
	Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h_29_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class InputAxisDelegateBinding."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Engine_Classes_Engine_InputAxisDelegateBinding_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
