// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
class UMaterialInstance;
class UMaterialInterface;
struct FLinearColor;
class UTexture;
#ifdef ENGINE_MaterialInstanceDynamic_generated_h
#error "MaterialInstanceDynamic.generated.h already included, missing '#pragma once' in MaterialInstanceDynamic.h"
#endif
#define ENGINE_MaterialInstanceDynamic_generated_h

#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_RPC_WRAPPERS \
 \
	DECLARE_FUNCTION(execCopyParameterOverrides) \
	{ \
		P_GET_OBJECT(UMaterialInstance,Z_Param_MaterialInstance); \
		P_FINISH; \
		this->CopyParameterOverrides(Z_Param_MaterialInstance); \
	} \
 \
	DECLARE_FUNCTION(execK2_CopyMaterialInstanceParameters) \
	{ \
		P_GET_OBJECT(UMaterialInterface,Z_Param_SourceMaterialToCopyFrom); \
		P_FINISH; \
		this->K2_CopyMaterialInstanceParameters(Z_Param_SourceMaterialToCopyFrom); \
	} \
 \
	DECLARE_FUNCTION(execK2_InterpolateMaterialInstanceParams) \
	{ \
		P_GET_OBJECT(UMaterialInstance,Z_Param_MaterialA); \
		P_GET_OBJECT(UMaterialInstance,Z_Param_MaterialB); \
		P_GET_PROPERTY(UFloatProperty,Z_Param_Alpha); \
		P_FINISH; \
		this->K2_InterpolateMaterialInstanceParams(Z_Param_MaterialA,Z_Param_MaterialB,Z_Param_Alpha); \
	} \
 \
	DECLARE_FUNCTION(execK2_GetVectorParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_FINISH; \
		*(FLinearColor*)Z_Param__Result=this->K2_GetVectorParameterValue(Z_Param_ParameterName); \
	} \
 \
	DECLARE_FUNCTION(execSetVectorParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_GET_STRUCT(FLinearColor,Z_Param_Value); \
		P_FINISH; \
		this->SetVectorParameterValue(Z_Param_ParameterName,Z_Param_Value); \
	} \
 \
	DECLARE_FUNCTION(execK2_GetTextureParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_FINISH; \
		*(UTexture**)Z_Param__Result=this->K2_GetTextureParameterValue(Z_Param_ParameterName); \
	} \
 \
	DECLARE_FUNCTION(execSetTextureParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_GET_OBJECT(UTexture,Z_Param_Value); \
		P_FINISH; \
		this->SetTextureParameterValue(Z_Param_ParameterName,Z_Param_Value); \
	} \
 \
	DECLARE_FUNCTION(execK2_GetScalarParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_FINISH; \
		*(float*)Z_Param__Result=this->K2_GetScalarParameterValue(Z_Param_ParameterName); \
	} \
 \
	DECLARE_FUNCTION(execSetScalarParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_GET_PROPERTY(UFloatProperty,Z_Param_Value); \
		P_FINISH; \
		this->SetScalarParameterValue(Z_Param_ParameterName,Z_Param_Value); \
	}


#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_RPC_WRAPPERS_NO_PURE_DECLS \
 \
	DECLARE_FUNCTION(execCopyParameterOverrides) \
	{ \
		P_GET_OBJECT(UMaterialInstance,Z_Param_MaterialInstance); \
		P_FINISH; \
		this->CopyParameterOverrides(Z_Param_MaterialInstance); \
	} \
 \
	DECLARE_FUNCTION(execK2_CopyMaterialInstanceParameters) \
	{ \
		P_GET_OBJECT(UMaterialInterface,Z_Param_SourceMaterialToCopyFrom); \
		P_FINISH; \
		this->K2_CopyMaterialInstanceParameters(Z_Param_SourceMaterialToCopyFrom); \
	} \
 \
	DECLARE_FUNCTION(execK2_InterpolateMaterialInstanceParams) \
	{ \
		P_GET_OBJECT(UMaterialInstance,Z_Param_MaterialA); \
		P_GET_OBJECT(UMaterialInstance,Z_Param_MaterialB); \
		P_GET_PROPERTY(UFloatProperty,Z_Param_Alpha); \
		P_FINISH; \
		this->K2_InterpolateMaterialInstanceParams(Z_Param_MaterialA,Z_Param_MaterialB,Z_Param_Alpha); \
	} \
 \
	DECLARE_FUNCTION(execK2_GetVectorParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_FINISH; \
		*(FLinearColor*)Z_Param__Result=this->K2_GetVectorParameterValue(Z_Param_ParameterName); \
	} \
 \
	DECLARE_FUNCTION(execSetVectorParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_GET_STRUCT(FLinearColor,Z_Param_Value); \
		P_FINISH; \
		this->SetVectorParameterValue(Z_Param_ParameterName,Z_Param_Value); \
	} \
 \
	DECLARE_FUNCTION(execK2_GetTextureParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_FINISH; \
		*(UTexture**)Z_Param__Result=this->K2_GetTextureParameterValue(Z_Param_ParameterName); \
	} \
 \
	DECLARE_FUNCTION(execSetTextureParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_GET_OBJECT(UTexture,Z_Param_Value); \
		P_FINISH; \
		this->SetTextureParameterValue(Z_Param_ParameterName,Z_Param_Value); \
	} \
 \
	DECLARE_FUNCTION(execK2_GetScalarParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_FINISH; \
		*(float*)Z_Param__Result=this->K2_GetScalarParameterValue(Z_Param_ParameterName); \
	} \
 \
	DECLARE_FUNCTION(execSetScalarParameterValue) \
	{ \
		P_GET_PROPERTY(UNameProperty,Z_Param_ParameterName); \
		P_GET_PROPERTY(UFloatProperty,Z_Param_Value); \
		P_FINISH; \
		this->SetScalarParameterValue(Z_Param_ParameterName,Z_Param_Value); \
	}


#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUMaterialInstanceDynamic(); \
	friend ENGINE_API class UClass* Z_Construct_UClass_UMaterialInstanceDynamic(); \
	public: \
	DECLARE_CLASS(UMaterialInstanceDynamic, UMaterialInstance, COMPILED_IN_FLAGS(0), 0, Engine, ENGINE_API) \
	DECLARE_SERIALIZER(UMaterialInstanceDynamic) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UMaterialInstanceDynamic*>(this); }


#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_INCLASS \
	private: \
	static void StaticRegisterNativesUMaterialInstanceDynamic(); \
	friend ENGINE_API class UClass* Z_Construct_UClass_UMaterialInstanceDynamic(); \
	public: \
	DECLARE_CLASS(UMaterialInstanceDynamic, UMaterialInstance, COMPILED_IN_FLAGS(0), 0, Engine, ENGINE_API) \
	DECLARE_SERIALIZER(UMaterialInstanceDynamic) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UMaterialInstanceDynamic*>(this); }


#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ENGINE_API UMaterialInstanceDynamic(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UMaterialInstanceDynamic) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ENGINE_API, UMaterialInstanceDynamic); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UMaterialInstanceDynamic); \
private: \
	/** Private copy-constructor, should never be used */ \
	ENGINE_API UMaterialInstanceDynamic(const UMaterialInstanceDynamic& InCopy); \
public:


#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ENGINE_API UMaterialInstanceDynamic(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	ENGINE_API UMaterialInstanceDynamic(const UMaterialInstanceDynamic& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ENGINE_API, UMaterialInstanceDynamic); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UMaterialInstanceDynamic); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UMaterialInstanceDynamic)


#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_8_PROLOG
#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_RPC_WRAPPERS \
	Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_INCLASS \
	Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h_11_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class MaterialInstanceDynamic."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Engine_Classes_Materials_MaterialInstanceDynamic_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
