// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "Private/GameplayTagsEditorModulePrivatePCH.h"
#include "GameplayTagsEditor.generated.dep.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
void EmptyLinkFunctionForGeneratedCodeGameplayTagsEditor() {}
	void UGameplayTagsK2Node_LiteralGameplayTag::StaticRegisterNativesUGameplayTagsK2Node_LiteralGameplayTag()
	{
	}
	IMPLEMENT_CLASS(UGameplayTagsK2Node_LiteralGameplayTag, 3061714914);
	void UGameplayTagsK2Node_MultiCompareBase::StaticRegisterNativesUGameplayTagsK2Node_MultiCompareBase()
	{
	}
	IMPLEMENT_CLASS(UGameplayTagsK2Node_MultiCompareBase, 85710713);
	void UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface::StaticRegisterNativesUGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface()
	{
	}
	IMPLEMENT_CLASS(UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface, 2825092556);
	void UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags::StaticRegisterNativesUGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags()
	{
	}
	IMPLEMENT_CLASS(UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags, 3985823530);
	void UGameplayTagsK2Node_MultiCompareGameplayTagContainer::StaticRegisterNativesUGameplayTagsK2Node_MultiCompareGameplayTagContainer()
	{
	}
	IMPLEMENT_CLASS(UGameplayTagsK2Node_MultiCompareGameplayTagContainer, 1379898022);
	void UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags::StaticRegisterNativesUGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags()
	{
	}
	IMPLEMENT_CLASS(UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags, 3975636859);
	void UGameplayTagsK2Node_SwitchGameplayTag::StaticRegisterNativesUGameplayTagsK2Node_SwitchGameplayTag()
	{
		FNativeFunctionRegistrar::RegisterFunction(UGameplayTagsK2Node_SwitchGameplayTag::StaticClass(),"NotEqual_TagTag",(Native)&UGameplayTagsK2Node_SwitchGameplayTag::execNotEqual_TagTag);
	}
	IMPLEMENT_CLASS(UGameplayTagsK2Node_SwitchGameplayTag, 2413687940);
	void UGameplayTagsK2Node_SwitchGameplayTagContainer::StaticRegisterNativesUGameplayTagsK2Node_SwitchGameplayTagContainer()
	{
		FNativeFunctionRegistrar::RegisterFunction(UGameplayTagsK2Node_SwitchGameplayTagContainer::StaticClass(),"NotEqual_TagContainerTagContainer",(Native)&UGameplayTagsK2Node_SwitchGameplayTagContainer::execNotEqual_TagContainerTagContainer);
	}
	IMPLEMENT_CLASS(UGameplayTagsK2Node_SwitchGameplayTagContainer, 2844147773);
#if USE_COMPILED_IN_NATIVES
// Cross Module References
	BLUEPRINTGRAPH_API class UClass* Z_Construct_UClass_UK2Node();
	GAMEPLAYTAGS_API class UScriptStruct* Z_Construct_UScriptStruct_FGameplayTag();
	BLUEPRINTGRAPH_API class UClass* Z_Construct_UClass_UK2Node_Switch();
	GAMEPLAYTAGS_API class UScriptStruct* Z_Construct_UScriptStruct_FGameplayTagContainer();

	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_LiteralGameplayTag_NoRegister();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_LiteralGameplayTag();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase_NoRegister();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface_NoRegister();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags_NoRegister();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainer_NoRegister();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainer();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags_NoRegister();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags();
	GAMEPLAYTAGSEDITOR_API class UFunction* Z_Construct_UFunction_UGameplayTagsK2Node_SwitchGameplayTag_NotEqual_TagTag();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTag_NoRegister();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTag();
	GAMEPLAYTAGSEDITOR_API class UFunction* Z_Construct_UFunction_UGameplayTagsK2Node_SwitchGameplayTagContainer_NotEqual_TagContainerTagContainer();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTagContainer_NoRegister();
	GAMEPLAYTAGSEDITOR_API class UClass* Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTagContainer();
	GAMEPLAYTAGSEDITOR_API class UPackage* Z_Construct_UPackage_GameplayTagsEditor();
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_LiteralGameplayTag_NoRegister()
	{
		return UGameplayTagsK2Node_LiteralGameplayTag::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_LiteralGameplayTag()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UK2Node();
			Z_Construct_UPackage_GameplayTagsEditor();
			OuterClass = UGameplayTagsK2Node_LiteralGameplayTag::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20000080;


				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayTagsK2Node_LiteralGameplayTag.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_LiteralGameplayTag.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayTagsK2Node_LiteralGameplayTag(Z_Construct_UClass_UGameplayTagsK2Node_LiteralGameplayTag, TEXT("UGameplayTagsK2Node_LiteralGameplayTag"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayTagsK2Node_LiteralGameplayTag);
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase_NoRegister()
	{
		return UGameplayTagsK2Node_MultiCompareBase::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UK2Node();
			Z_Construct_UPackage_GameplayTagsEditor();
			OuterClass = UGameplayTagsK2Node_MultiCompareBase::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20000080;


PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_PinNames = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PinNames"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(PinNames, UGameplayTagsK2Node_MultiCompareBase), 0x0000000000000000);
				UProperty* NewProp_PinNames_Inner = new(EC_InternalUseOnlyConstructor, NewProp_PinNames, TEXT("PinNames"), RF_Public|RF_Transient|RF_Native) UNameProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000);
				UProperty* NewProp_NumberOfPins = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("NumberOfPins"), RF_Public|RF_Transient|RF_Native) UIntProperty(CPP_PROPERTY_BASE(NumberOfPins, UGameplayTagsK2Node_MultiCompareBase), 0x0000000000000001);
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayTagsK2Node_MultiCompareBase.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_MultiCompareBase.h"));
				MetaData->SetValue(NewProp_PinNames, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_MultiCompareBase.h"));
				MetaData->SetValue(NewProp_NumberOfPins, TEXT("Category"), TEXT("PinOptions"));
				MetaData->SetValue(NewProp_NumberOfPins, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_MultiCompareBase.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayTagsK2Node_MultiCompareBase(Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase, TEXT("UGameplayTagsK2Node_MultiCompareBase"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayTagsK2Node_MultiCompareBase);
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface_NoRegister()
	{
		return UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase();
			Z_Construct_UPackage_GameplayTagsEditor();
			OuterClass = UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20000080;


				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayTagsK2Node_MultiCompareGameplayTagAssetInterface.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_MultiCompareGameplayTagAssetInterface.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface(Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface, TEXT("UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterface);
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags_NoRegister()
	{
		return UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase();
			Z_Construct_UPackage_GameplayTagsEditor();
			OuterClass = UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20000080;


				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags(Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags, TEXT("UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayTagsK2Node_MultiCompareGameplayTagAssetInterfaceSingleTags);
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainer_NoRegister()
	{
		return UGameplayTagsK2Node_MultiCompareGameplayTagContainer::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainer()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase();
			Z_Construct_UPackage_GameplayTagsEditor();
			OuterClass = UGameplayTagsK2Node_MultiCompareGameplayTagContainer::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20000080;


				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayTagsK2Node_MultiCompareGameplayTagContainer.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_MultiCompareGameplayTagContainer.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainer(Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainer, TEXT("UGameplayTagsK2Node_MultiCompareGameplayTagContainer"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayTagsK2Node_MultiCompareGameplayTagContainer);
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags_NoRegister()
	{
		return UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareBase();
			Z_Construct_UPackage_GameplayTagsEditor();
			OuterClass = UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20000080;


				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags(Z_Construct_UClass_UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags, TEXT("UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayTagsK2Node_MultiCompareGameplayTagContainerSingleTags);
	UFunction* Z_Construct_UFunction_UGameplayTagsK2Node_SwitchGameplayTag_NotEqual_TagTag()
	{
		struct GameplayTagsK2Node_SwitchGameplayTag_eventNotEqual_TagTag_Parms
		{
			FGameplayTag A;
			FString B;
			bool ReturnValue;
		};
		UObject* Outer=Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTag();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("NotEqual_TagTag"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x14082401, 65535, sizeof(GameplayTagsK2Node_SwitchGameplayTag_eventNotEqual_TagTag_Parms));
			CPP_BOOL_PROPERTY_BITMASK_STRUCT(ReturnValue, GameplayTagsK2Node_SwitchGameplayTag_eventNotEqual_TagTag_Parms, bool);
			UProperty* NewProp_ReturnValue = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("ReturnValue"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(ReturnValue, GameplayTagsK2Node_SwitchGameplayTag_eventNotEqual_TagTag_Parms), 0x0000000000000580, CPP_BOOL_PROPERTY_BITMASK(ReturnValue, GameplayTagsK2Node_SwitchGameplayTag_eventNotEqual_TagTag_Parms), sizeof(bool), true);
			UProperty* NewProp_B = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("B"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(B, GameplayTagsK2Node_SwitchGameplayTag_eventNotEqual_TagTag_Parms), 0x0000000000000080);
			UProperty* NewProp_A = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("A"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(A, GameplayTagsK2Node_SwitchGameplayTag_eventNotEqual_TagTag_Parms), 0x0000000000000080, Z_Construct_UScriptStruct_FGameplayTag());
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("PinOptions"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_SwitchGameplayTag.h"));
#endif
		}
		return ReturnFunction;
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTag_NoRegister()
	{
		return UGameplayTagsK2Node_SwitchGameplayTag::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTag()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UK2Node_Switch();
			Z_Construct_UPackage_GameplayTagsEditor();
			OuterClass = UGameplayTagsK2Node_SwitchGameplayTag::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20080080;

				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayTagsK2Node_SwitchGameplayTag_NotEqual_TagTag());

PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_PinNames = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PinNames"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(PinNames, UGameplayTagsK2Node_SwitchGameplayTag), 0x0000000000000000);
				UProperty* NewProp_PinNames_Inner = new(EC_InternalUseOnlyConstructor, NewProp_PinNames, TEXT("PinNames"), RF_Public|RF_Transient|RF_Native) UNameProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000);
				UProperty* NewProp_PinTags = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PinTags"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(PinTags, UGameplayTagsK2Node_SwitchGameplayTag), 0x0000000000000001);
				UProperty* NewProp_PinTags_Inner = new(EC_InternalUseOnlyConstructor, NewProp_PinTags, TEXT("PinTags"), RF_Public|RF_Transient|RF_Native) UStructProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000, Z_Construct_UScriptStruct_FGameplayTag());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayTagsK2Node_SwitchGameplayTag_NotEqual_TagTag()); // 1073132891
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayTagsK2Node_SwitchGameplayTag.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_SwitchGameplayTag.h"));
				MetaData->SetValue(NewProp_PinNames, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_SwitchGameplayTag.h"));
				MetaData->SetValue(NewProp_PinNames, TEXT("ToolTip"), TEXT("UPROPERTY(EditAnywhere, Category = PinOptions)\nbool UseInputsOnGraph;"));
				MetaData->SetValue(NewProp_PinTags, TEXT("Category"), TEXT("PinOptions"));
				MetaData->SetValue(NewProp_PinTags, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_SwitchGameplayTag.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayTagsK2Node_SwitchGameplayTag(Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTag, TEXT("UGameplayTagsK2Node_SwitchGameplayTag"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayTagsK2Node_SwitchGameplayTag);
	UFunction* Z_Construct_UFunction_UGameplayTagsK2Node_SwitchGameplayTagContainer_NotEqual_TagContainerTagContainer()
	{
		struct GameplayTagsK2Node_SwitchGameplayTagContainer_eventNotEqual_TagContainerTagContainer_Parms
		{
			FGameplayTagContainer A;
			FString B;
			bool ReturnValue;
		};
		UObject* Outer=Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTagContainer();
		static UFunction* ReturnFunction = NULL;
		if (!ReturnFunction)
		{
			ReturnFunction = new(EC_InternalUseOnlyConstructor, Outer, TEXT("NotEqual_TagContainerTagContainer"), RF_Public|RF_Transient|RF_Native) UFunction(FObjectInitializer(), NULL, 0x14082401, 65535, sizeof(GameplayTagsK2Node_SwitchGameplayTagContainer_eventNotEqual_TagContainerTagContainer_Parms));
			CPP_BOOL_PROPERTY_BITMASK_STRUCT(ReturnValue, GameplayTagsK2Node_SwitchGameplayTagContainer_eventNotEqual_TagContainerTagContainer_Parms, bool);
			UProperty* NewProp_ReturnValue = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("ReturnValue"), RF_Public|RF_Transient|RF_Native) UBoolProperty(FObjectInitializer(), EC_CppProperty, CPP_BOOL_PROPERTY_OFFSET(ReturnValue, GameplayTagsK2Node_SwitchGameplayTagContainer_eventNotEqual_TagContainerTagContainer_Parms), 0x0000000000000580, CPP_BOOL_PROPERTY_BITMASK(ReturnValue, GameplayTagsK2Node_SwitchGameplayTagContainer_eventNotEqual_TagContainerTagContainer_Parms), sizeof(bool), true);
			UProperty* NewProp_B = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("B"), RF_Public|RF_Transient|RF_Native) UStrProperty(CPP_PROPERTY_BASE(B, GameplayTagsK2Node_SwitchGameplayTagContainer_eventNotEqual_TagContainerTagContainer_Parms), 0x0000000000000080);
			UProperty* NewProp_A = new(EC_InternalUseOnlyConstructor, ReturnFunction, TEXT("A"), RF_Public|RF_Transient|RF_Native) UStructProperty(CPP_PROPERTY_BASE(A, GameplayTagsK2Node_SwitchGameplayTagContainer_eventNotEqual_TagContainerTagContainer_Parms), 0x0000000000000080, Z_Construct_UScriptStruct_FGameplayTagContainer());
			ReturnFunction->Bind();
			ReturnFunction->StaticLink();
#if WITH_METADATA
			UMetaData* MetaData = ReturnFunction->GetOutermost()->GetMetaData();
			MetaData->SetValue(ReturnFunction, TEXT("Category"), TEXT("PinOptions"));
			MetaData->SetValue(ReturnFunction, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_SwitchGameplayTagContainer.h"));
#endif
		}
		return ReturnFunction;
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTagContainer_NoRegister()
	{
		return UGameplayTagsK2Node_SwitchGameplayTagContainer::StaticClass();
	}
	UClass* Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTagContainer()
	{
		static UClass* OuterClass = NULL;
		if (!OuterClass)
		{
			Z_Construct_UClass_UK2Node_Switch();
			Z_Construct_UPackage_GameplayTagsEditor();
			OuterClass = UGameplayTagsK2Node_SwitchGameplayTagContainer::StaticClass();
			if (!(OuterClass->ClassFlags & CLASS_Constructed))
			{
				UObjectForceRegistration(OuterClass);
				OuterClass->ClassFlags |= 0x20080080;

				OuterClass->LinkChild(Z_Construct_UFunction_UGameplayTagsK2Node_SwitchGameplayTagContainer_NotEqual_TagContainerTagContainer());

PRAGMA_DISABLE_DEPRECATION_WARNINGS
				UProperty* NewProp_PinNames = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PinNames"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(PinNames, UGameplayTagsK2Node_SwitchGameplayTagContainer), 0x0000000000000000);
				UProperty* NewProp_PinNames_Inner = new(EC_InternalUseOnlyConstructor, NewProp_PinNames, TEXT("PinNames"), RF_Public|RF_Transient|RF_Native) UNameProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000);
				UProperty* NewProp_PinContainers = new(EC_InternalUseOnlyConstructor, OuterClass, TEXT("PinContainers"), RF_Public|RF_Transient|RF_Native) UArrayProperty(CPP_PROPERTY_BASE(PinContainers, UGameplayTagsK2Node_SwitchGameplayTagContainer), 0x0000000000000001);
				UProperty* NewProp_PinContainers_Inner = new(EC_InternalUseOnlyConstructor, NewProp_PinContainers, TEXT("PinContainers"), RF_Public|RF_Transient|RF_Native) UStructProperty(FObjectInitializer(), EC_CppProperty, 0, 0x0000000000000000, Z_Construct_UScriptStruct_FGameplayTagContainer());
PRAGMA_ENABLE_DEPRECATION_WARNINGS
				OuterClass->AddFunctionToFunctionMap(Z_Construct_UFunction_UGameplayTagsK2Node_SwitchGameplayTagContainer_NotEqual_TagContainerTagContainer()); // 684582590
				OuterClass->StaticLink();
#if WITH_METADATA
				UMetaData* MetaData = OuterClass->GetOutermost()->GetMetaData();
				MetaData->SetValue(OuterClass, TEXT("IncludePath"), TEXT("GameplayTagsK2Node_SwitchGameplayTagContainer.h"));
				MetaData->SetValue(OuterClass, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_SwitchGameplayTagContainer.h"));
				MetaData->SetValue(NewProp_PinNames, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_SwitchGameplayTagContainer.h"));
				MetaData->SetValue(NewProp_PinNames, TEXT("ToolTip"), TEXT("UPROPERTY(EditAnywhere, Category = PinOptions)\nbool UseInputsOnGraph;"));
				MetaData->SetValue(NewProp_PinContainers, TEXT("Category"), TEXT("PinOptions"));
				MetaData->SetValue(NewProp_PinContainers, TEXT("ModuleRelativePath"), TEXT("Classes/GameplayTagsK2Node_SwitchGameplayTagContainer.h"));
#endif
			}
		}
		check(OuterClass->GetClass());
		return OuterClass;
	}
	static FCompiledInDefer Z_CompiledInDefer_UClass_UGameplayTagsK2Node_SwitchGameplayTagContainer(Z_Construct_UClass_UGameplayTagsK2Node_SwitchGameplayTagContainer, TEXT("UGameplayTagsK2Node_SwitchGameplayTagContainer"));
	DEFINE_VTABLE_PTR_HELPER_CTOR(UGameplayTagsK2Node_SwitchGameplayTagContainer);
	UPackage* Z_Construct_UPackage_GameplayTagsEditor()
	{
		static UPackage* ReturnPackage = NULL;
		if (!ReturnPackage)
		{
			ReturnPackage = CastChecked<UPackage>(StaticFindObjectFast(UPackage::StaticClass(), NULL, FName(TEXT("/Script/GameplayTagsEditor")), false, false));
			ReturnPackage->SetPackageFlags(PKG_CompiledIn | 0x00000000);
			FGuid Guid;
			Guid.A = 0xBD9BAC00;
			Guid.B = 0x1CE80C54;
			Guid.C = 0x00000000;
			Guid.D = 0x00000000;
			ReturnPackage->SetGuid(Guid);

		}
		return ReturnPackage;
	}
#endif

PRAGMA_ENABLE_DEPRECATION_WARNINGS
