// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
class UObject;
class APlayerController;
class UCreateSessionCallbackProxy;
#ifdef ONLINESUBSYSTEMUTILS_CreateSessionCallbackProxy_generated_h
#error "CreateSessionCallbackProxy.generated.h already included, missing '#pragma once' in CreateSessionCallbackProxy.h"
#endif
#define ONLINESUBSYSTEMUTILS_CreateSessionCallbackProxy_generated_h

#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_RPC_WRAPPERS \
 \
	DECLARE_FUNCTION(execCreateSession) \
	{ \
		P_GET_OBJECT(UObject,Z_Param_WorldContextObject); \
		P_GET_OBJECT(APlayerController,Z_Param_PlayerController); \
		P_GET_PROPERTY(UIntProperty,Z_Param_PublicConnections); \
		P_GET_UBOOL(Z_Param_bUseLAN); \
		P_FINISH; \
		*(UCreateSessionCallbackProxy**)Z_Param__Result=UCreateSessionCallbackProxy::CreateSession(Z_Param_WorldContextObject,Z_Param_PlayerController,Z_Param_PublicConnections,Z_Param_bUseLAN); \
	}


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_RPC_WRAPPERS_NO_PURE_DECLS \
 \
	DECLARE_FUNCTION(execCreateSession) \
	{ \
		P_GET_OBJECT(UObject,Z_Param_WorldContextObject); \
		P_GET_OBJECT(APlayerController,Z_Param_PlayerController); \
		P_GET_PROPERTY(UIntProperty,Z_Param_PublicConnections); \
		P_GET_UBOOL(Z_Param_bUseLAN); \
		P_FINISH; \
		*(UCreateSessionCallbackProxy**)Z_Param__Result=UCreateSessionCallbackProxy::CreateSession(Z_Param_WorldContextObject,Z_Param_PlayerController,Z_Param_PublicConnections,Z_Param_bUseLAN); \
	}


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUCreateSessionCallbackProxy(); \
	friend ONLINESUBSYSTEMUTILS_API class UClass* Z_Construct_UClass_UCreateSessionCallbackProxy(); \
	public: \
	DECLARE_CLASS(UCreateSessionCallbackProxy, UOnlineBlueprintCallProxyBase, COMPILED_IN_FLAGS(0), 0, OnlineSubsystemUtils, ONLINESUBSYSTEMUTILS_API) \
	DECLARE_SERIALIZER(UCreateSessionCallbackProxy) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UCreateSessionCallbackProxy*>(this); }


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_INCLASS \
	private: \
	static void StaticRegisterNativesUCreateSessionCallbackProxy(); \
	friend ONLINESUBSYSTEMUTILS_API class UClass* Z_Construct_UClass_UCreateSessionCallbackProxy(); \
	public: \
	DECLARE_CLASS(UCreateSessionCallbackProxy, UOnlineBlueprintCallProxyBase, COMPILED_IN_FLAGS(0), 0, OnlineSubsystemUtils, ONLINESUBSYSTEMUTILS_API) \
	DECLARE_SERIALIZER(UCreateSessionCallbackProxy) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UCreateSessionCallbackProxy*>(this); }


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ONLINESUBSYSTEMUTILS_API UCreateSessionCallbackProxy(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UCreateSessionCallbackProxy) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ONLINESUBSYSTEMUTILS_API, UCreateSessionCallbackProxy); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UCreateSessionCallbackProxy); \
private: \
	/** Private copy-constructor, should never be used */ \
	ONLINESUBSYSTEMUTILS_API UCreateSessionCallbackProxy(const UCreateSessionCallbackProxy& InCopy); \
public:


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ONLINESUBSYSTEMUTILS_API UCreateSessionCallbackProxy(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	ONLINESUBSYSTEMUTILS_API UCreateSessionCallbackProxy(const UCreateSessionCallbackProxy& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ONLINESUBSYSTEMUTILS_API, UCreateSessionCallbackProxy); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UCreateSessionCallbackProxy); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UCreateSessionCallbackProxy)


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_7_PROLOG
#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_RPC_WRAPPERS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_INCLASS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h_10_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class CreateSessionCallbackProxy."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_CreateSessionCallbackProxy_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
