// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
class APlayerController;
class UObject;
class ULogoutCallbackProxy;
#ifdef ONLINESUBSYSTEMUTILS_LogoutCallbackProxy_generated_h
#error "LogoutCallbackProxy.generated.h already included, missing '#pragma once' in LogoutCallbackProxy.h"
#endif
#define ONLINESUBSYSTEMUTILS_LogoutCallbackProxy_generated_h

#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_10_DELEGATE \
struct _Script_OnlineSubsystemUtils_eventOnlineLogoutResult_Parms \
{ \
	APlayerController* PlayerController; \
}; \
static inline void FOnlineLogoutResult_DelegateWrapper(const FMulticastScriptDelegate& OnlineLogoutResult, APlayerController* PlayerController) \
{ \
	_Script_OnlineSubsystemUtils_eventOnlineLogoutResult_Parms Parms; \
	Parms.PlayerController=PlayerController; \
	OnlineLogoutResult.ProcessMulticastDelegate<UObject>(&Parms); \
}




#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_RPC_WRAPPERS \
 \
	DECLARE_FUNCTION(execLogout) \
	{ \
		P_GET_OBJECT(UObject,Z_Param_WorldContextObject); \
		P_GET_OBJECT(APlayerController,Z_Param_PlayerController); \
		P_FINISH; \
		*(ULogoutCallbackProxy**)Z_Param__Result=ULogoutCallbackProxy::Logout(Z_Param_WorldContextObject,Z_Param_PlayerController); \
	}


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_RPC_WRAPPERS_NO_PURE_DECLS \
 \
	DECLARE_FUNCTION(execLogout) \
	{ \
		P_GET_OBJECT(UObject,Z_Param_WorldContextObject); \
		P_GET_OBJECT(APlayerController,Z_Param_PlayerController); \
		P_FINISH; \
		*(ULogoutCallbackProxy**)Z_Param__Result=ULogoutCallbackProxy::Logout(Z_Param_WorldContextObject,Z_Param_PlayerController); \
	}


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesULogoutCallbackProxy(); \
	friend ONLINESUBSYSTEMUTILS_API class UClass* Z_Construct_UClass_ULogoutCallbackProxy(); \
	public: \
	DECLARE_CLASS(ULogoutCallbackProxy, UBlueprintAsyncActionBase, COMPILED_IN_FLAGS(0), 0, OnlineSubsystemUtils, ONLINESUBSYSTEMUTILS_API) \
	DECLARE_SERIALIZER(ULogoutCallbackProxy) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<ULogoutCallbackProxy*>(this); }


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_INCLASS \
	private: \
	static void StaticRegisterNativesULogoutCallbackProxy(); \
	friend ONLINESUBSYSTEMUTILS_API class UClass* Z_Construct_UClass_ULogoutCallbackProxy(); \
	public: \
	DECLARE_CLASS(ULogoutCallbackProxy, UBlueprintAsyncActionBase, COMPILED_IN_FLAGS(0), 0, OnlineSubsystemUtils, ONLINESUBSYSTEMUTILS_API) \
	DECLARE_SERIALIZER(ULogoutCallbackProxy) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<ULogoutCallbackProxy*>(this); }


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ONLINESUBSYSTEMUTILS_API ULogoutCallbackProxy(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(ULogoutCallbackProxy) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ONLINESUBSYSTEMUTILS_API, ULogoutCallbackProxy); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(ULogoutCallbackProxy); \
private: \
	/** Private copy-constructor, should never be used */ \
	ONLINESUBSYSTEMUTILS_API ULogoutCallbackProxy(const ULogoutCallbackProxy& InCopy); \
public:


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_ENHANCED_CONSTRUCTORS \
private: \
	/** Private copy-constructor, should never be used */ \
	ONLINESUBSYSTEMUTILS_API ULogoutCallbackProxy(const ULogoutCallbackProxy& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ONLINESUBSYSTEMUTILS_API, ULogoutCallbackProxy); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(ULogoutCallbackProxy); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(ULogoutCallbackProxy)


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_12_PROLOG
#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_RPC_WRAPPERS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_INCLASS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h_15_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Online_OnlineSubsystemUtils_Classes_LogoutCallbackProxy_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
