// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef ONLINESUBSYSTEMUTILS_OnlineBeaconHost_generated_h
#error "OnlineBeaconHost.generated.h already included, missing '#pragma once' in OnlineBeaconHost.h"
#endif
#define ONLINESUBSYSTEMUTILS_OnlineBeaconHost_generated_h

#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_RPC_WRAPPERS
#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesAOnlineBeaconHost(); \
	friend ONLINESUBSYSTEMUTILS_API class UClass* Z_Construct_UClass_AOnlineBeaconHost(); \
	public: \
	DECLARE_CLASS(AOnlineBeaconHost, AOnlineBeacon, COMPILED_IN_FLAGS(0 | CLASS_Transient | CLASS_Config), 0, OnlineSubsystemUtils, NO_API) \
	DECLARE_SERIALIZER(AOnlineBeaconHost) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<AOnlineBeaconHost*>(this); }


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_INCLASS \
	private: \
	static void StaticRegisterNativesAOnlineBeaconHost(); \
	friend ONLINESUBSYSTEMUTILS_API class UClass* Z_Construct_UClass_AOnlineBeaconHost(); \
	public: \
	DECLARE_CLASS(AOnlineBeaconHost, AOnlineBeacon, COMPILED_IN_FLAGS(0 | CLASS_Transient | CLASS_Config), 0, OnlineSubsystemUtils, NO_API) \
	DECLARE_SERIALIZER(AOnlineBeaconHost) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<AOnlineBeaconHost*>(this); }


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API AOnlineBeaconHost(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(AOnlineBeaconHost) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AOnlineBeaconHost); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AOnlineBeaconHost); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API AOnlineBeaconHost(const AOnlineBeaconHost& InCopy); \
public:


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API AOnlineBeaconHost(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API AOnlineBeaconHost(const AOnlineBeaconHost& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, AOnlineBeaconHost); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(AOnlineBeaconHost); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(AOnlineBeaconHost)


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_20_PROLOG
#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_RPC_WRAPPERS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_INCLASS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h_23_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class OnlineBeaconHost."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_OnlineBeaconHost_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
