// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef ONLINESUBSYSTEMUTILS_PartyBeaconHost_generated_h
#error "PartyBeaconHost.generated.h already included, missing '#pragma once' in PartyBeaconHost.h"
#endif
#define ONLINESUBSYSTEMUTILS_PartyBeaconHost_generated_h

#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_RPC_WRAPPERS
#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesAPartyBeaconHost(); \
	friend ONLINESUBSYSTEMUTILS_API class UClass* Z_Construct_UClass_APartyBeaconHost(); \
	public: \
	DECLARE_CLASS(APartyBeaconHost, AOnlineBeaconHostObject, COMPILED_IN_FLAGS(0 | CLASS_Transient | CLASS_Config), 0, OnlineSubsystemUtils, NO_API) \
	DECLARE_SERIALIZER(APartyBeaconHost) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<APartyBeaconHost*>(this); }


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_INCLASS \
	private: \
	static void StaticRegisterNativesAPartyBeaconHost(); \
	friend ONLINESUBSYSTEMUTILS_API class UClass* Z_Construct_UClass_APartyBeaconHost(); \
	public: \
	DECLARE_CLASS(APartyBeaconHost, AOnlineBeaconHostObject, COMPILED_IN_FLAGS(0 | CLASS_Transient | CLASS_Config), 0, OnlineSubsystemUtils, NO_API) \
	DECLARE_SERIALIZER(APartyBeaconHost) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<APartyBeaconHost*>(this); }


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API APartyBeaconHost(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(APartyBeaconHost) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, APartyBeaconHost); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(APartyBeaconHost); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API APartyBeaconHost(const APartyBeaconHost& InCopy); \
public:


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API APartyBeaconHost(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API APartyBeaconHost(const APartyBeaconHost& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, APartyBeaconHost); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(APartyBeaconHost); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(APartyBeaconHost)


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_44_PROLOG
#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_RPC_WRAPPERS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_INCLASS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h_47_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class PartyBeaconHost."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Online_OnlineSubsystemUtils_Public_PartyBeaconHost_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
