// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#ifndef HTML5PLATFORMEDITOR_HTML5SDKSettings_generated_h
	#include "Private/HTML5SDKSettings.h"
#endif
#ifndef HTML5PLATFORMEDITOR_HTML5TargetSettings_generated_h
	#include "Classes/HTML5TargetSettings.h"
#endif
