// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#ifndef WORLDBROWSER_WorldTileDetails_generated_h
	#include "Private/Tiles/WorldTileDetails.h"
#endif
