// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef MOVIESCENE_MovieScenePossessable_generated_h
#error "MovieScenePossessable.generated.h already included, missing '#pragma once' in MovieScenePossessable.h"
#endif
#define MOVIESCENE_MovieScenePossessable_generated_h

#define Engine_Source_Runtime_MovieScene_Public_MovieScenePossessable_h_14_GENERATED_BODY \
	friend MOVIESCENE_API class UScriptStruct* Z_Construct_UScriptStruct_FMovieScenePossessable(); \
	MOVIESCENE_API static class UScriptStruct* StaticStruct();


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_MovieScene_Public_MovieScenePossessable_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
