// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef WEBBROWSER_WebJSFunction_generated_h
#error "WebJSFunction.generated.h already included, missing '#pragma once' in WebJSFunction.h"
#endif
#define WEBBROWSER_WebJSFunction_generated_h

#define Engine_Source_Runtime_WebBrowser_Public_WebJSFunction_h_50_GENERATED_BODY \
	friend WEBBROWSER_API class UScriptStruct* Z_Construct_UScriptStruct_FWebJSFunction(); \
	static class UScriptStruct* StaticStruct();


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_WebBrowser_Public_WebJSFunction_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
