// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
class UGameplayAbility;
class UObject;
struct FGameplayTag;
class UAbilityTask_WaitAbilityActivate;
#ifdef GAMEPLAYABILITIES_AbilityTask_WaitAbilityActivate_generated_h
#error "AbilityTask_WaitAbilityActivate.generated.h already included, missing '#pragma once' in AbilityTask_WaitAbilityActivate.h"
#endif
#define GAMEPLAYABILITIES_AbilityTask_WaitAbilityActivate_generated_h

#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_7_DELEGATE \
struct _Script_GameplayAbilities_eventWaitAbilityActivateDelegate_Parms \
{ \
	UGameplayAbility* ActivatedAbility; \
}; \
static inline void FWaitAbilityActivateDelegate_DelegateWrapper(const FMulticastScriptDelegate& WaitAbilityActivateDelegate, UGameplayAbility* ActivatedAbility) \
{ \
	_Script_GameplayAbilities_eventWaitAbilityActivateDelegate_Parms Parms; \
	Parms.ActivatedAbility=ActivatedAbility; \
	WaitAbilityActivateDelegate.ProcessMulticastDelegate<UObject>(&Parms); \
}




#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_RPC_WRAPPERS \
 \
	DECLARE_FUNCTION(execWaitForAbilityActivate) \
	{ \
		P_GET_OBJECT(UObject,Z_Param_WorldContextObject); \
		P_GET_STRUCT(FGameplayTag,Z_Param_WithTag); \
		P_GET_STRUCT(FGameplayTag,Z_Param_WithoutTag); \
		P_GET_UBOOL(Z_Param_IncludeTriggeredAbilities); \
		P_GET_UBOOL(Z_Param_TriggerOnce); \
		P_FINISH; \
		*(UAbilityTask_WaitAbilityActivate**)Z_Param__Result=UAbilityTask_WaitAbilityActivate::WaitForAbilityActivate(Z_Param_WorldContextObject,Z_Param_WithTag,Z_Param_WithoutTag,Z_Param_IncludeTriggeredAbilities,Z_Param_TriggerOnce); \
	} \
 \
	DECLARE_FUNCTION(execOnAbilityActivate) \
	{ \
		P_GET_OBJECT(UGameplayAbility,Z_Param_ActivatedAbility); \
		P_FINISH; \
		this->OnAbilityActivate(Z_Param_ActivatedAbility); \
	}


#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_RPC_WRAPPERS_NO_PURE_DECLS \
 \
	DECLARE_FUNCTION(execWaitForAbilityActivate) \
	{ \
		P_GET_OBJECT(UObject,Z_Param_WorldContextObject); \
		P_GET_STRUCT(FGameplayTag,Z_Param_WithTag); \
		P_GET_STRUCT(FGameplayTag,Z_Param_WithoutTag); \
		P_GET_UBOOL(Z_Param_IncludeTriggeredAbilities); \
		P_GET_UBOOL(Z_Param_TriggerOnce); \
		P_FINISH; \
		*(UAbilityTask_WaitAbilityActivate**)Z_Param__Result=UAbilityTask_WaitAbilityActivate::WaitForAbilityActivate(Z_Param_WorldContextObject,Z_Param_WithTag,Z_Param_WithoutTag,Z_Param_IncludeTriggeredAbilities,Z_Param_TriggerOnce); \
	} \
 \
	DECLARE_FUNCTION(execOnAbilityActivate) \
	{ \
		P_GET_OBJECT(UGameplayAbility,Z_Param_ActivatedAbility); \
		P_FINISH; \
		this->OnAbilityActivate(Z_Param_ActivatedAbility); \
	}


#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUAbilityTask_WaitAbilityActivate(); \
	friend GAMEPLAYABILITIES_API class UClass* Z_Construct_UClass_UAbilityTask_WaitAbilityActivate(); \
	public: \
	DECLARE_CLASS(UAbilityTask_WaitAbilityActivate, UAbilityTask, COMPILED_IN_FLAGS(0), 0, GameplayAbilities, GAMEPLAYABILITIES_API) \
	DECLARE_SERIALIZER(UAbilityTask_WaitAbilityActivate) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UAbilityTask_WaitAbilityActivate*>(this); }


#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_INCLASS \
	private: \
	static void StaticRegisterNativesUAbilityTask_WaitAbilityActivate(); \
	friend GAMEPLAYABILITIES_API class UClass* Z_Construct_UClass_UAbilityTask_WaitAbilityActivate(); \
	public: \
	DECLARE_CLASS(UAbilityTask_WaitAbilityActivate, UAbilityTask, COMPILED_IN_FLAGS(0), 0, GameplayAbilities, GAMEPLAYABILITIES_API) \
	DECLARE_SERIALIZER(UAbilityTask_WaitAbilityActivate) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UAbilityTask_WaitAbilityActivate*>(this); }


#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	GAMEPLAYABILITIES_API UAbilityTask_WaitAbilityActivate(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UAbilityTask_WaitAbilityActivate) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(GAMEPLAYABILITIES_API, UAbilityTask_WaitAbilityActivate); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UAbilityTask_WaitAbilityActivate); \
private: \
	/** Private copy-constructor, should never be used */ \
	GAMEPLAYABILITIES_API UAbilityTask_WaitAbilityActivate(const UAbilityTask_WaitAbilityActivate& InCopy); \
public:


#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	GAMEPLAYABILITIES_API UAbilityTask_WaitAbilityActivate(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	GAMEPLAYABILITIES_API UAbilityTask_WaitAbilityActivate(const UAbilityTask_WaitAbilityActivate& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(GAMEPLAYABILITIES_API, UAbilityTask_WaitAbilityActivate); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UAbilityTask_WaitAbilityActivate); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UAbilityTask_WaitAbilityActivate)


#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_14_PROLOG
#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_RPC_WRAPPERS \
	Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_INCLASS \
	Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h_17_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class AbilityTask_WaitAbilityActivate."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_GameplayAbilities_Public_Abilities_Tasks_AbilityTask_WaitAbilityActivate_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
