// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef GAMEPLAYABILITIES_GameplayCueManager_generated_h
#error "GameplayCueManager.generated.h already included, missing '#pragma once' in GameplayCueManager.h"
#endif
#define GAMEPLAYABILITIES_GameplayCueManager_generated_h

#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_62_GENERATED_BODY \
	friend GAMEPLAYABILITIES_API class UScriptStruct* Z_Construct_UScriptStruct_FGameplayCuePendingExecute(); \
	GAMEPLAYABILITIES_API static class UScriptStruct* StaticStruct();


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_RPC_WRAPPERS
#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUGameplayCueManager(); \
	friend GAMEPLAYABILITIES_API class UClass* Z_Construct_UClass_UGameplayCueManager(); \
	public: \
	DECLARE_CLASS(UGameplayCueManager, UDataAsset, COMPILED_IN_FLAGS(0), 0, GameplayAbilities, NO_API) \
	DECLARE_SERIALIZER(UGameplayCueManager) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UGameplayCueManager*>(this); }


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_INCLASS \
	private: \
	static void StaticRegisterNativesUGameplayCueManager(); \
	friend GAMEPLAYABILITIES_API class UClass* Z_Construct_UClass_UGameplayCueManager(); \
	public: \
	DECLARE_CLASS(UGameplayCueManager, UDataAsset, COMPILED_IN_FLAGS(0), 0, GameplayAbilities, NO_API) \
	DECLARE_SERIALIZER(UGameplayCueManager) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UGameplayCueManager*>(this); }


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UGameplayCueManager(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UGameplayCueManager) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UGameplayCueManager); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UGameplayCueManager); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UGameplayCueManager(const UGameplayCueManager& InCopy); \
public:


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UGameplayCueManager(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UGameplayCueManager(const UGameplayCueManager& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UGameplayCueManager); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UGameplayCueManager); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UGameplayCueManager)


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_111_PROLOG
#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_RPC_WRAPPERS \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_INCLASS \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h_114_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class GameplayCueManager."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_GameplayAbilities_Public_GameplayCueManager_h


#define FOREACH_ENUM_EGAMEPLAYCUEPAYLOADTYPE(op) \
	op(EGameplayCuePayloadType::EffectContext) \
	op(EGameplayCuePayloadType::CueParameters) \
	op(EGameplayCuePayloadType::FromSpec) 
PRAGMA_ENABLE_DEPRECATION_WARNINGS
