// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef GAMEPLAYABILITIES_GameplayEffectExtension_generated_h
#error "GameplayEffectExtension.generated.h already included, missing '#pragma once' in GameplayEffectExtension.h"
#endif
#define GAMEPLAYABILITIES_GameplayEffectExtension_generated_h

#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_RPC_WRAPPERS
#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUGameplayEffectExtension(); \
	friend GAMEPLAYABILITIES_API class UClass* Z_Construct_UClass_UGameplayEffectExtension(); \
	public: \
	DECLARE_CLASS(UGameplayEffectExtension, UObject, COMPILED_IN_FLAGS(0), 0, GameplayAbilities, NO_API) \
	DECLARE_SERIALIZER(UGameplayEffectExtension) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const { return const_cast<UGameplayEffectExtension*>(this); }


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_INCLASS \
	private: \
	static void StaticRegisterNativesUGameplayEffectExtension(); \
	friend GAMEPLAYABILITIES_API class UClass* Z_Construct_UClass_UGameplayEffectExtension(); \
	public: \
	DECLARE_CLASS(UGameplayEffectExtension, UObject, COMPILED_IN_FLAGS(0), 0, GameplayAbilities, NO_API) \
	DECLARE_SERIALIZER(UGameplayEffectExtension) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const { return const_cast<UGameplayEffectExtension*>(this); }


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UGameplayEffectExtension(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UGameplayEffectExtension) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UGameplayEffectExtension); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UGameplayEffectExtension); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UGameplayEffectExtension(const UGameplayEffectExtension& InCopy); \
public:


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UGameplayEffectExtension(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UGameplayEffectExtension(const UGameplayEffectExtension& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UGameplayEffectExtension); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UGameplayEffectExtension); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UGameplayEffectExtension)


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_27_PROLOG
#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_RPC_WRAPPERS \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_INCLASS \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h_30_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class GameplayEffectExtension."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_GameplayAbilities_Public_GameplayEffectExtension_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
