// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef LANDSCAPE_LandscapeGrassType_generated_h
#error "LandscapeGrassType.generated.h already included, missing '#pragma once' in LandscapeGrassType.h"
#endif
#define LANDSCAPE_LandscapeGrassType_generated_h

#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_10_GENERATED_BODY \
	friend LANDSCAPE_API class UScriptStruct* Z_Construct_UScriptStruct_FGrassVariety(); \
	LANDSCAPE_API static class UScriptStruct* StaticStruct();


#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_RPC_WRAPPERS
#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesULandscapeGrassType(); \
	friend LANDSCAPE_API class UClass* Z_Construct_UClass_ULandscapeGrassType(); \
	public: \
	DECLARE_CLASS(ULandscapeGrassType, UObject, COMPILED_IN_FLAGS(0), 0, Landscape, LANDSCAPE_API) \
	DECLARE_SERIALIZER(ULandscapeGrassType) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const { return const_cast<ULandscapeGrassType*>(this); }


#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_INCLASS \
	private: \
	static void StaticRegisterNativesULandscapeGrassType(); \
	friend LANDSCAPE_API class UClass* Z_Construct_UClass_ULandscapeGrassType(); \
	public: \
	DECLARE_CLASS(ULandscapeGrassType, UObject, COMPILED_IN_FLAGS(0), 0, Landscape, LANDSCAPE_API) \
	DECLARE_SERIALIZER(ULandscapeGrassType) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const { return const_cast<ULandscapeGrassType*>(this); }


#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	LANDSCAPE_API ULandscapeGrassType(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(ULandscapeGrassType) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(LANDSCAPE_API, ULandscapeGrassType); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(ULandscapeGrassType); \
private: \
	/** Private copy-constructor, should never be used */ \
	LANDSCAPE_API ULandscapeGrassType(const ULandscapeGrassType& InCopy); \
public:


#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	LANDSCAPE_API ULandscapeGrassType(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	LANDSCAPE_API ULandscapeGrassType(const ULandscapeGrassType& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(LANDSCAPE_API, ULandscapeGrassType); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(ULandscapeGrassType); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(ULandscapeGrassType)


#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_64_PROLOG
#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_RPC_WRAPPERS \
	Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_INCLASS \
	Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h_67_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class LandscapeGrassType."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Landscape_Classes_LandscapeGrassType_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
