// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef UNREALED_NiagaraNodeOp_generated_h
#error "NiagaraNodeOp.generated.h already included, missing '#pragma once' in NiagaraNodeOp.h"
#endif
#define UNREALED_NiagaraNodeOp_generated_h

#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_RPC_WRAPPERS
#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUNiagaraNodeOp(); \
	friend UNREALED_API class UClass* Z_Construct_UClass_UNiagaraNodeOp(); \
	public: \
	DECLARE_CLASS(UNiagaraNodeOp, UNiagaraNode, COMPILED_IN_FLAGS(0), 0, UnrealEd, UNREALED_API) \
	DECLARE_SERIALIZER(UNiagaraNodeOp) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UNiagaraNodeOp*>(this); }


#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_INCLASS \
	private: \
	static void StaticRegisterNativesUNiagaraNodeOp(); \
	friend UNREALED_API class UClass* Z_Construct_UClass_UNiagaraNodeOp(); \
	public: \
	DECLARE_CLASS(UNiagaraNodeOp, UNiagaraNode, COMPILED_IN_FLAGS(0), 0, UnrealEd, UNREALED_API) \
	DECLARE_SERIALIZER(UNiagaraNodeOp) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UNiagaraNodeOp*>(this); }


#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	UNREALED_API UNiagaraNodeOp(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UNiagaraNodeOp) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(UNREALED_API, UNiagaraNodeOp); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UNiagaraNodeOp); \
private: \
	/** Private copy-constructor, should never be used */ \
	UNREALED_API UNiagaraNodeOp(const UNiagaraNodeOp& InCopy); \
public:


#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	UNREALED_API UNiagaraNodeOp(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	UNREALED_API UNiagaraNodeOp(const UNiagaraNodeOp& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(UNREALED_API, UNiagaraNodeOp); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UNiagaraNodeOp); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UNiagaraNodeOp)


#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_6_PROLOG
#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_RPC_WRAPPERS \
	Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_INCLASS \
	Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_INCLASS_NO_PURE_DECLS \
	Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h_9_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class NiagaraNodeOp."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Editor_UnrealEd_Classes_Niagara_NiagaraNodeOp_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
