// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef UNREALED_SequenceExporterT3D_generated_h
#error "SequenceExporterT3D.generated.h already included, missing '#pragma once' in SequenceExporterT3D.h"
#endif
#define UNREALED_SequenceExporterT3D_generated_h

#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_RPC_WRAPPERS
#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUSequenceExporterT3D(); \
	friend UNREALED_API class UClass* Z_Construct_UClass_USequenceExporterT3D(); \
	public: \
	DECLARE_CLASS(USequenceExporterT3D, UExporter, COMPILED_IN_FLAGS(0 | CLASS_Transient), 0, UnrealEd, NO_API) \
	DECLARE_SERIALIZER(USequenceExporterT3D) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<USequenceExporterT3D*>(this); }


#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_INCLASS \
	private: \
	static void StaticRegisterNativesUSequenceExporterT3D(); \
	friend UNREALED_API class UClass* Z_Construct_UClass_USequenceExporterT3D(); \
	public: \
	DECLARE_CLASS(USequenceExporterT3D, UExporter, COMPILED_IN_FLAGS(0 | CLASS_Transient), 0, UnrealEd, NO_API) \
	DECLARE_SERIALIZER(USequenceExporterT3D) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<USequenceExporterT3D*>(this); }


#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API USequenceExporterT3D(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(USequenceExporterT3D) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, USequenceExporterT3D); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(USequenceExporterT3D); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API USequenceExporterT3D(const USequenceExporterT3D& InCopy); \
public:


#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_ENHANCED_CONSTRUCTORS \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API USequenceExporterT3D(const USequenceExporterT3D& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, USequenceExporterT3D); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(USequenceExporterT3D); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(USequenceExporterT3D)


#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_10_PROLOG
#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_RPC_WRAPPERS \
	Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_INCLASS \
	Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_INCLASS_NO_PURE_DECLS \
	Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h_14_ENHANCED_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Editor_UnrealEd_Classes_Exporters_SequenceExporterT3D_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
