// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#ifndef MATERIALSHADERQUALITYSETTINGS_ShaderPlatformQualitySettings_generated_h
	#include "Classes/ShaderPlatformQualitySettings.h"
#endif
#ifndef MATERIALSHADERQUALITYSETTINGS_MaterialShaderQualitySettings_generated_h
	#include "Classes/MaterialShaderQualitySettings.h"
#endif
#ifndef MATERIALSHADERQUALITYSETTINGS_ShaderQualityOverridesListItem_generated_h
	#include "Private/ShaderQualityOverridesListItem.h"
#endif
