// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef ANIMGRAPH_K2Node_TransitionRuleGetter_generated_h
#error "K2Node_TransitionRuleGetter.generated.h already included, missing '#pragma once' in K2Node_TransitionRuleGetter.h"
#endif
#define ANIMGRAPH_K2Node_TransitionRuleGetter_generated_h

#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_RPC_WRAPPERS
#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUK2Node_TransitionRuleGetter(); \
	friend ANIMGRAPH_API class UClass* Z_Construct_UClass_UK2Node_TransitionRuleGetter(); \
	public: \
	DECLARE_CLASS(UK2Node_TransitionRuleGetter, UK2Node, COMPILED_IN_FLAGS(0), 0, AnimGraph, ANIMGRAPH_API) \
	DECLARE_SERIALIZER(UK2Node_TransitionRuleGetter) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UK2Node_TransitionRuleGetter*>(this); }


#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_INCLASS \
	private: \
	static void StaticRegisterNativesUK2Node_TransitionRuleGetter(); \
	friend ANIMGRAPH_API class UClass* Z_Construct_UClass_UK2Node_TransitionRuleGetter(); \
	public: \
	DECLARE_CLASS(UK2Node_TransitionRuleGetter, UK2Node, COMPILED_IN_FLAGS(0), 0, AnimGraph, ANIMGRAPH_API) \
	DECLARE_SERIALIZER(UK2Node_TransitionRuleGetter) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UK2Node_TransitionRuleGetter*>(this); }


#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ANIMGRAPH_API UK2Node_TransitionRuleGetter(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UK2Node_TransitionRuleGetter) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ANIMGRAPH_API, UK2Node_TransitionRuleGetter); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UK2Node_TransitionRuleGetter); \
private: \
	/** Private copy-constructor, should never be used */ \
	ANIMGRAPH_API UK2Node_TransitionRuleGetter(const UK2Node_TransitionRuleGetter& InCopy); \
public:


#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	ANIMGRAPH_API UK2Node_TransitionRuleGetter(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	ANIMGRAPH_API UK2Node_TransitionRuleGetter(const UK2Node_TransitionRuleGetter& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(ANIMGRAPH_API, UK2Node_TransitionRuleGetter); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UK2Node_TransitionRuleGetter); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UK2Node_TransitionRuleGetter)


#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_28_PROLOG
#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_RPC_WRAPPERS \
	Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_INCLASS \
	Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_INCLASS_NO_PURE_DECLS \
	Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h_31_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class K2Node_TransitionRuleGetter."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Editor_AnimGraph_Classes_K2Node_TransitionRuleGetter_h


#define FOREACH_ENUM_ETRANSITIONGETTER(op) \
	op(ETransitionGetter::AnimationAsset_GetCurrentTime) \
	op(ETransitionGetter::AnimationAsset_GetLength) \
	op(ETransitionGetter::AnimationAsset_GetCurrentTimeFraction) \
	op(ETransitionGetter::AnimationAsset_GetTimeFromEnd) \
	op(ETransitionGetter::AnimationAsset_GetTimeFromEndFraction) \
	op(ETransitionGetter::CurrentState_ElapsedTime) \
	op(ETransitionGetter::CurrentState_GetBlendWeight) \
	op(ETransitionGetter::CurrentTransitionDuration) \
	op(ETransitionGetter::ArbitraryState_GetBlendWeight) 
PRAGMA_ENABLE_DEPRECATION_WARNINGS
