// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef AIGRAPH_AIGraph_generated_h
#error "AIGraph.generated.h already included, missing '#pragma once' in AIGraph.h"
#endif
#define AIGRAPH_AIGraph_generated_h

#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_RPC_WRAPPERS
#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUAIGraph(); \
	friend AIGRAPH_API class UClass* Z_Construct_UClass_UAIGraph(); \
	public: \
	DECLARE_CLASS(UAIGraph, UEdGraph, COMPILED_IN_FLAGS(0), 0, AIGraph, NO_API) \
	DECLARE_SERIALIZER(UAIGraph) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UAIGraph*>(this); }


#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_INCLASS \
	private: \
	static void StaticRegisterNativesUAIGraph(); \
	friend AIGRAPH_API class UClass* Z_Construct_UClass_UAIGraph(); \
	public: \
	DECLARE_CLASS(UAIGraph, UEdGraph, COMPILED_IN_FLAGS(0), 0, AIGraph, NO_API) \
	DECLARE_SERIALIZER(UAIGraph) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UAIGraph*>(this); }


#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UAIGraph(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UAIGraph) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UAIGraph); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UAIGraph); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UAIGraph(const UAIGraph& InCopy); \
public:


#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UAIGraph(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UAIGraph(const UAIGraph& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UAIGraph); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UAIGraph); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UAIGraph)


#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_6_PROLOG
#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_RPC_WRAPPERS \
	Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_INCLASS \
	Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_INCLASS_NO_PURE_DECLS \
	Engine_Source_Editor_AIGraph_Classes_AIGraph_h_9_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class AIGraph."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Editor_AIGraph_Classes_AIGraph_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
