// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
struct FVector2D;
#ifdef UMG_MenuAnchor_generated_h
#error "MenuAnchor.generated.h already included, missing '#pragma once' in MenuAnchor.h"
#endif
#define UMG_MenuAnchor_generated_h

#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_7_DELEGATE \
struct _Script_UMG_eventOnMenuOpenChangedEvent_Parms \
{ \
	bool bIsOpen; \
}; \
static inline void FOnMenuOpenChangedEvent_DelegateWrapper(const FMulticastScriptDelegate& OnMenuOpenChangedEvent, bool bIsOpen) \
{ \
	_Script_UMG_eventOnMenuOpenChangedEvent_Parms Parms; \
	Parms.bIsOpen=bIsOpen ? true : false; \
	OnMenuOpenChangedEvent.ProcessMulticastDelegate<UObject>(&Parms); \
}




#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_RPC_WRAPPERS \
 \
	DECLARE_FUNCTION(execHasOpenSubMenus) \
	{ \
		P_FINISH; \
		*(bool*)Z_Param__Result=this->HasOpenSubMenus(); \
	} \
 \
	DECLARE_FUNCTION(execGetMenuPosition) \
	{ \
		P_FINISH; \
		*(FVector2D*)Z_Param__Result=this->GetMenuPosition(); \
	} \
 \
	DECLARE_FUNCTION(execShouldOpenDueToClick) \
	{ \
		P_FINISH; \
		*(bool*)Z_Param__Result=this->ShouldOpenDueToClick(); \
	} \
 \
	DECLARE_FUNCTION(execIsOpen) \
	{ \
		P_FINISH; \
		*(bool*)Z_Param__Result=this->IsOpen(); \
	} \
 \
	DECLARE_FUNCTION(execClose) \
	{ \
		P_FINISH; \
		this->Close(); \
	} \
 \
	DECLARE_FUNCTION(execOpen) \
	{ \
		P_GET_UBOOL(Z_Param_bFocusMenu); \
		P_FINISH; \
		this->Open(Z_Param_bFocusMenu); \
	} \
 \
	DECLARE_FUNCTION(execToggleOpen) \
	{ \
		P_GET_UBOOL(Z_Param_bFocusOnOpen); \
		P_FINISH; \
		this->ToggleOpen(Z_Param_bFocusOnOpen); \
	}


#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_RPC_WRAPPERS_NO_PURE_DECLS \
 \
	DECLARE_FUNCTION(execHasOpenSubMenus) \
	{ \
		P_FINISH; \
		*(bool*)Z_Param__Result=this->HasOpenSubMenus(); \
	} \
 \
	DECLARE_FUNCTION(execGetMenuPosition) \
	{ \
		P_FINISH; \
		*(FVector2D*)Z_Param__Result=this->GetMenuPosition(); \
	} \
 \
	DECLARE_FUNCTION(execShouldOpenDueToClick) \
	{ \
		P_FINISH; \
		*(bool*)Z_Param__Result=this->ShouldOpenDueToClick(); \
	} \
 \
	DECLARE_FUNCTION(execIsOpen) \
	{ \
		P_FINISH; \
		*(bool*)Z_Param__Result=this->IsOpen(); \
	} \
 \
	DECLARE_FUNCTION(execClose) \
	{ \
		P_FINISH; \
		this->Close(); \
	} \
 \
	DECLARE_FUNCTION(execOpen) \
	{ \
		P_GET_UBOOL(Z_Param_bFocusMenu); \
		P_FINISH; \
		this->Open(Z_Param_bFocusMenu); \
	} \
 \
	DECLARE_FUNCTION(execToggleOpen) \
	{ \
		P_GET_UBOOL(Z_Param_bFocusOnOpen); \
		P_FINISH; \
		this->ToggleOpen(Z_Param_bFocusOnOpen); \
	}


#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUMenuAnchor(); \
	friend UMG_API class UClass* Z_Construct_UClass_UMenuAnchor(); \
	public: \
	DECLARE_CLASS(UMenuAnchor, UContentWidget, COMPILED_IN_FLAGS(0), 0, UMG, NO_API) \
	DECLARE_SERIALIZER(UMenuAnchor) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UMenuAnchor*>(this); }


#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_INCLASS \
	private: \
	static void StaticRegisterNativesUMenuAnchor(); \
	friend UMG_API class UClass* Z_Construct_UClass_UMenuAnchor(); \
	public: \
	DECLARE_CLASS(UMenuAnchor, UContentWidget, COMPILED_IN_FLAGS(0), 0, UMG, NO_API) \
	DECLARE_SERIALIZER(UMenuAnchor) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UMenuAnchor*>(this); }


#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UMenuAnchor(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UMenuAnchor) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UMenuAnchor); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UMenuAnchor); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UMenuAnchor(const UMenuAnchor& InCopy); \
public:


#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UMenuAnchor(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UMenuAnchor(const UMenuAnchor& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UMenuAnchor); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UMenuAnchor); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UMenuAnchor)


#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_15_PROLOG
#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_RPC_WRAPPERS \
	Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_INCLASS \
	Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h_18_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class MenuAnchor."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_UMG_Public_Components_MenuAnchor_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
