// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
struct FVector2D;
#ifdef UMG_Spacer_generated_h
#error "Spacer.generated.h already included, missing '#pragma once' in Spacer.h"
#endif
#define UMG_Spacer_generated_h

#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_RPC_WRAPPERS \
 \
	DECLARE_FUNCTION(execSetSize) \
	{ \
		P_GET_STRUCT(FVector2D,Z_Param_InSize); \
		P_FINISH; \
		this->SetSize(Z_Param_InSize); \
	}


#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_RPC_WRAPPERS_NO_PURE_DECLS \
 \
	DECLARE_FUNCTION(execSetSize) \
	{ \
		P_GET_STRUCT(FVector2D,Z_Param_InSize); \
		P_FINISH; \
		this->SetSize(Z_Param_InSize); \
	}


#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUSpacer(); \
	friend UMG_API class UClass* Z_Construct_UClass_USpacer(); \
	public: \
	DECLARE_CLASS(USpacer, UWidget, COMPILED_IN_FLAGS(0), 0, UMG, NO_API) \
	DECLARE_SERIALIZER(USpacer) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<USpacer*>(this); }


#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_INCLASS \
	private: \
	static void StaticRegisterNativesUSpacer(); \
	friend UMG_API class UClass* Z_Construct_UClass_USpacer(); \
	public: \
	DECLARE_CLASS(USpacer, UWidget, COMPILED_IN_FLAGS(0), 0, UMG, NO_API) \
	DECLARE_SERIALIZER(USpacer) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<USpacer*>(this); }


#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API USpacer(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(USpacer) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, USpacer); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(USpacer); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API USpacer(const USpacer& InCopy); \
public:


#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API USpacer(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API USpacer(const USpacer& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, USpacer); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(USpacer); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(USpacer)


#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_12_PROLOG
#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_RPC_WRAPPERS \
	Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_INCLASS \
	Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_UMG_Public_Components_Spacer_h_15_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class Spacer."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_UMG_Public_Components_Spacer_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
