// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	Boilerplate C++ definitions for a single module.
	This is automatically generated by UnrealHeaderTool.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#ifndef GEOMETRYCACHE_ActorFactoryGeometryCache_generated_h
	#include "Private/ActorFactoryGeometryCache.h"
#endif
#ifndef GEOMETRYCACHE_GeometryCacheTrack_generated_h
	#include "Classes/GeometryCacheTrack.h"
#endif
#ifndef GEOMETRYCACHE_GeometryCache_generated_h
	#include "Classes/GeometryCache.h"
#endif
#ifndef GEOMETRYCACHE_GeometryCacheActor_generated_h
	#include "Classes/GeometryCacheActor.h"
#endif
#ifndef GEOMETRYCACHE_GeometryCacheComponent_generated_h
	#include "Classes/GeometryCacheComponent.h"
#endif
#ifndef GEOMETRYCACHE_GeometryCacheMeshData_generated_h
	#include "Classes/GeometryCacheMeshData.h"
#endif
#ifndef GEOMETRYCACHE_GeometryCacheTrackFlipbookAnimation_generated_h
	#include "Classes/GeometryCacheTrackFlipbookAnimation.h"
#endif
#ifndef GEOMETRYCACHE_GeometryCacheTrackTransformAnimation_generated_h
	#include "Classes/GeometryCacheTrackTransformAnimation.h"
#endif
