// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef AIMODULE_AISenseConfig_Hearing_generated_h
#error "AISenseConfig_Hearing.generated.h already included, missing '#pragma once' in AISenseConfig_Hearing.h"
#endif
#define AIMODULE_AISenseConfig_Hearing_generated_h

#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_RPC_WRAPPERS
#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUAISenseConfig_Hearing(); \
	friend AIMODULE_API class UClass* Z_Construct_UClass_UAISenseConfig_Hearing(); \
	public: \
	DECLARE_CLASS(UAISenseConfig_Hearing, UAISenseConfig, COMPILED_IN_FLAGS(0 | CLASS_Config), 0, AIModule, NO_API) \
	DECLARE_SERIALIZER(UAISenseConfig_Hearing) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UAISenseConfig_Hearing*>(this); }


#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_INCLASS \
	private: \
	static void StaticRegisterNativesUAISenseConfig_Hearing(); \
	friend AIMODULE_API class UClass* Z_Construct_UClass_UAISenseConfig_Hearing(); \
	public: \
	DECLARE_CLASS(UAISenseConfig_Hearing, UAISenseConfig, COMPILED_IN_FLAGS(0 | CLASS_Config), 0, AIModule, NO_API) \
	DECLARE_SERIALIZER(UAISenseConfig_Hearing) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UAISenseConfig_Hearing*>(this); }


#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UAISenseConfig_Hearing(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UAISenseConfig_Hearing) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UAISenseConfig_Hearing); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UAISenseConfig_Hearing); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UAISenseConfig_Hearing(const UAISenseConfig_Hearing& InCopy); \
public:


#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_ENHANCED_CONSTRUCTORS \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UAISenseConfig_Hearing(const UAISenseConfig_Hearing& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UAISenseConfig_Hearing); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UAISenseConfig_Hearing); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UAISenseConfig_Hearing)


#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_10_PROLOG
#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_RPC_WRAPPERS \
	Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_INCLASS \
	Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h_13_ENHANCED_CONSTRUCTORS \
private: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_AIModule_Classes_Perception_AISenseConfig_Hearing_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
