// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

PRAGMA_DISABLE_DEPRECATION_WARNINGS
#ifdef NIAGARA_NiagaraComponent_generated_h
#error "NiagaraComponent.generated.h already included, missing '#pragma once' in NiagaraComponent.h"
#endif
#define NIAGARA_NiagaraComponent_generated_h

#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_RPC_WRAPPERS
#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_RPC_WRAPPERS_NO_PURE_DECLS
#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_INCLASS_NO_PURE_DECLS \
	private: \
	static void StaticRegisterNativesUNiagaraComponent(); \
	friend NIAGARA_API class UClass* Z_Construct_UClass_UNiagaraComponent(); \
	public: \
	DECLARE_CLASS(UNiagaraComponent, UPrimitiveComponent, COMPILED_IN_FLAGS(0), 0, Niagara, NO_API) \
	DECLARE_SERIALIZER(UNiagaraComponent) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UNiagaraComponent*>(this); }


#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_INCLASS \
	private: \
	static void StaticRegisterNativesUNiagaraComponent(); \
	friend NIAGARA_API class UClass* Z_Construct_UClass_UNiagaraComponent(); \
	public: \
	DECLARE_CLASS(UNiagaraComponent, UPrimitiveComponent, COMPILED_IN_FLAGS(0), 0, Niagara, NO_API) \
	DECLARE_SERIALIZER(UNiagaraComponent) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC}; \
	virtual UObject* _getUObject() const override { return const_cast<UNiagaraComponent*>(this); }


#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_STANDARD_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UNiagaraComponent(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UNiagaraComponent) \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UNiagaraComponent); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UNiagaraComponent); \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UNiagaraComponent(const UNiagaraComponent& InCopy); \
public:


#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_ENHANCED_CONSTRUCTORS \
	/** Standard constructor, called after all reflected properties have been initialized */ \
	NO_API UNiagaraComponent(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get()) : Super(ObjectInitializer) { }; \
private: \
	/** Private copy-constructor, should never be used */ \
	NO_API UNiagaraComponent(const UNiagaraComponent& InCopy); \
public: \
	DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, UNiagaraComponent); \
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER(UNiagaraComponent); \
	DEFINE_DEFAULT_OBJECT_INITIALIZER_CONSTRUCTOR_CALL(UNiagaraComponent)


#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_121_PROLOG
#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_GENERATED_BODY_LEGACY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_RPC_WRAPPERS \
	Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_INCLASS \
	Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_STANDARD_CONSTRUCTORS \
public: \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#define Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_GENERATED_BODY \
PRAGMA_DISABLE_DEPRECATION_WARNINGS \
public: \
	Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_RPC_WRAPPERS_NO_PURE_DECLS \
	Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_INCLASS_NO_PURE_DECLS \
	Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h_124_ENHANCED_CONSTRUCTORS \
static_assert(false, "Unknown access specifier for GENERATED_BODY() macro in class NiagaraComponent."); \
PRAGMA_ENABLE_DEPRECATION_WARNINGS


#undef CURRENT_FILE_ID
#define CURRENT_FILE_ID Engine_Source_Runtime_Niagara_Public_NiagaraComponent_h


PRAGMA_ENABLE_DEPRECATION_WARNINGS
